// Real SQLite and password hashing. External services are mocked; no payments/messages are sent.
import assert from 'node:assert/strict';
import jsQR from 'jsqr';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {readFile,mkdtemp,rm,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
const require=createRequire(import.meta.url),esbuild=createRequire(require.resolve('vite/package.json'))('esbuild');
const dir=await mkdtemp(path.join(tmpdir(),'cca-check-')),sql=new DatabaseSync(':memory:');
for(const file of (await readdir('drizzle')).filter(x=>x.endsWith('.sql')).sort())sql.exec(await readFile('drizzle/'+file,'utf8'));
class Statement{constructor(query,values=[]){this.query=query;this.values=values}bind(...values){return new Statement(this.query,values)}async first(){return sql.prepare(this.query).get(...this.values)??null}async all(){return {results:sql.prepare(this.query).all(...this.values)}}async run(){const r=sql.prepare(this.query).run(...this.values);return {success:true,meta:{changes:Number(r.changes)}}}}
let beforeBatch=null;
const database={prepare:q=>new Statement(q),async batch(queries){if(beforeBatch)beforeBatch(queries);sql.exec('BEGIN');try{const out=[];for(const q of queries)out.push(await q.run());sql.exec('COMMIT');return out}catch(e){sql.exec('ROLLBACK');throw e}}};
const objects=new Map();
globalThis.__testEnv={DB:database,APP_SECRET:'fixture-application-secret',ADMIN_SETUP_CODE:'fixture-setup-secret',PUBLIC_URL:'https://local.test',BUCKET:{put:async(key,bytes,options)=>{objects.set(key,{bytes,httpMetadata:options.httpMetadata})},get:async key=>{const o=objects.get(key);return o?{body:o.bytes,httpMetadata:o.httpMetadata}:null},delete:async key=>{objects.delete(key)}}};globalThis.__testUser=null;
await esbuild.build({entryPoints:[path.resolve('app/api/[...path]/route.ts')],bundle:true,platform:'node',format:'esm',outfile:path.join(dir,'route.mjs'),logLevel:'silent',plugins:[{name:'boundaries',setup(build){build.onResolve({filter:/^cloudflare:workers$/},()=>({path:'runtime',namespace:'mock'}));build.onResolve({filter:/chatgpt-auth$/},()=>({path:'identity',namespace:'mock'}));build.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:a.path==='runtime'?'export const env=globalThis.__testEnv':'export async function getChatGPTUser(){return globalThis.__testUser}',loader:'js'}))}}]});
const route=await import(path.join(dir,'route.mjs'));const origin='https://local.test';let count=0;const ok=(v,label)=>{assert.ok(v,label);count++;console.log('PASS',label)};
function decodeQR(html){
 const svg=html.match(/<svg[^>]*viewBox="0 0 (\d+) (\d+)"[^>]*>.*?<\/svg>/s);
 assert.ok(svg,'Receipt has an inline QR code');
 const side=Number(svg[1]),scale=5,width=side*scale,pixels=new Uint8ClampedArray(width*width*4).fill(255);
 for(const [,x,y] of svg[0].matchAll(/M(\d+) (\d+)h1v1h-1z/g))for(let dy=0;dy<scale;dy++)for(let dx=0;dx<scale;dx++){
  const index=((Number(y)*scale+dy)*width+Number(x)*scale+dx)*4;pixels[index]=pixels[index+1]=pixels[index+2]=0;
 }
 return jsQR(pixels,width,width)?.data;
}
function client(ip){const jar=new Map();return {jar,async request(endpoint,method='GET',data,headers={}){const req=new Request(origin+'/api/'+endpoint,{method,headers:{Origin:origin,'Content-Type':'application/json','cf-connecting-ip':ip,Cookie:[...jar].map(([k,v])=>k+'='+v).join('; '),...headers},...(data===undefined?{}:{body:JSON.stringify(data)})});const response=await route[method](req);for(const c of response.headers.getSetCookie()){const [key,value]=c.split(';')[0].split('=');if(c.includes('Max-Age=0'))jar.delete(key);else jar.set(key,value)}const isJSON=response.headers.get('content-type')?.includes('json');return {status:response.status,headers:response.headers,...isJSON?await response.json():{html:await response.text()}}}}}
const owner=client('10.0.0.1'),alice=client('10.0.0.2'),bob=client('10.0.0.3'),visitor=client('10.0.0.4'),stranger=client('10.0.0.5');
const password='Uma senha de teste 123!';let r;
try{
r=await stranger.request('catalog');ok(r.status===200&&r.products.length===0,'Catalog is public and hides sample products');
r=await stranger.request('profile');ok(r.status===401,'Anonymous profile requires customer or guest session');
globalThis.__testUser={userId:'platform-owner',displayName:'Owner'};
r=await owner.request('admin/setup','POST',{code:'fixture-setup-secret'});ok(r.status===200,'Administrative ownership remains protected by platform identity');
r=await owner.request('admin/product','POST',{name:'Brownie',description:'Chocolate artesanal',price:1400,category:'Brownies',image:'/images/brownies.jpg',active:true});ok(r.status===200,'Owner can publish product');const productId=r.id;
const store={name:'Confeitando com Amor',open:true,paymentProvider:'mercadopago',lat:-23.55,lng:-46.63,hoursMode:'open',storeAddress:'Rua Um, 20, Centro, São Paulo - SP, 01000-000',baseFee:500,perKm:150,maxKm:15,pickup:true,cash:true,prepMin:40,prepMax:60,whatsapp:'',pixKey:'',pixName:'',pixCity:'',whatsappEnabled:false};
r=await owner.request('admin/settings','PUT',store);ok(r.status===200,'Store with real product and cash pickup can open');
r=await owner.request('admin/integrations','PUT',{orsKey:'fixture-ors-key',mpToken:'fixture-mp-token',mpWebhookSecret:'fixture-mp-signature',pbToken:'fixture-pb-token'});ok(r.status===200,'Payment credentials are configured without provider login');
ok(!sql.prepare("SELECT value FROM settings WHERE key='integrations'").get().value.includes('fixture-mp-token'),'Integration credentials remain encrypted');
r=await owner.request('admin/connect/mercadopago','POST',{});ok(r.status===404,'Removed bank OAuth entry is unavailable');
r=await owner.request('admin/whatsapp/config');ok(r.status===404,'Removed QR signup entry is unavailable');
globalThis.__testUser=null;
r=await alice.request('customer/register','POST',{name:'Alice Cliente',email:'Alice@Example.Test',password:'short'});ok(r.status===422,'Registration rejects short password');
r=await alice.request('customer/register','POST',{name:'Alice Cliente',email:'Alice@Example.Test',password});ok(r.status===201&&r.recoveryCode,'Customer registers with email/password and receives recovery code');const recovery=r.recoveryCode;
const authCookie=r.headers.get('set-cookie');ok(authCookie.includes('HttpOnly')&&authCookie.includes('Secure')&&authCookie.includes('SameSite=Lax'),'Customer cookie is HttpOnly, Secure and SameSite');
const customer=sql.prepare('SELECT * FROM customers WHERE email=?').get('alice@example.test');ok(customer.password_hash.startsWith('scrypt:16384:8:5:')&&!customer.password_hash.includes(password),'Password stored as salted scrypt, not plaintext');
const rawSession=[...alice.jar.values()][0];ok(!sql.prepare('SELECT token_hash FROM customer_sessions').all().some(s=>s.token_hash===rawSession),'Only hashed session tokens are stored');
r=await alice.request('customer/session');ok(r.signedIn&&r.user.name==='Alice Cliente','Customer session survives a new request');
r=await alice.request('admin/data');ok(r.status===401||r.status===403,'Customer login never grants administrative access');
r=await alice.request('profile','PUT',{name:'Alice Cliente',cpf:'52998224725',phone:'11999999999',whatsappConsent:false});ok(r.status===200,'Customer profile can be saved');
r=await alice.request('customer/logout','POST',{});ok(r.status===200,'Customer can sign out');
r=await alice.request('customer/session');ok(!r.signedIn,'Sign-out revokes access');
r=await alice.request('customer/login','POST',{email:'alice@example.test',password:'incorrect'});ok(r.status===401,'Wrong password rejected');
r=await alice.request('customer/login','POST',{email:'ALICE@example.test',password});ok(r.status===200,'Email login normalizes case');
r=await bob.request('customer/register','POST',{name:'Bob Cliente',email:'bob@example.test',password});ok(r.status===201,'Second independent customer can register');
r=await alice.request('products/'+productId+'/like','PUT',{liked:true});ok(r.likes===1,'Registered customer can like');
r=await alice.request('products/'+productId+'/like','PUT',{liked:true});ok(r.likes===1,'Repeated like does not duplicate count');
r=await alice.request('products/'+productId+'/comments','POST',{body:'Muito bom!'});ok(r.status===201,'Registered customer can comment');
r=await bob.request('products/'+productId+'/comments');const comment=r.comments[0];ok(comment.name==='Alice'&&!comment.canDelete&&!JSON.stringify(r).includes(customer.id),'Comments expose only public name and permitted controls');
r=await bob.request('products/'+productId+'/comments','DELETE',{id:comment.id});ok(r.status===403,'Other customer cannot delete comment');
r=await visitor.request('customer/guest','POST',{});ok(r.status===200&&r.guest,'Guest starts checkout without email or password');
r=await visitor.request('products/'+productId+'/like','PUT',{liked:true});ok(r.status===401,'Guest cannot use login-only likes');
r=await visitor.request('customer/session');ok(r.guest&&!r.signedIn,'Guest session is distinct from a customer account');
let routePayload;
globalThis.fetch=async(url,options)=>{if(String(url)==='https://api.openrouteservice.org/v2/directions/driving-car/json'){routePayload=JSON.parse(options.body);return Response.json({routes:[{summary:{distance:5250}}]})}throw Error('Unexpected external request: '+url)};
const address={cep:'01000-000',street:'Rua Dois',number:'50',district:'Centro',city:'São Paulo',state:'SP',complement:'',location:{lat:-23.550321,lng:-46.633112,accuracy:12,source:'gps',confirmed:true}};
r=await visitor.request('quote','POST',{...address,location:undefined});ok(r.status===422,'Delivery quote requires the exact point in addition to address');
r=await visitor.request('quote','POST',{...address,location:{...address.location,confirmed:false}});ok(r.status===422,'Unconfirmed map point cannot price a delivery');
r=await visitor.request('quote','POST',{...address,location:{...address.location,lat:91}});ok(r.status===422,'Coordinates outside valid geographic bounds are rejected');
r=await visitor.request('quote','POST',address);ok(r.status===200&&r.distance===5250&&r.fee===1288,'Guest freight uses returned driving route and cent rounding');const quoteId=r.id;ok(routePayload.coordinates[1][1]===address.location.lat&&routePayload.coordinates[1][0]===address.location.lng,'Freight uses the exact coordinates selected by customer');
ok(routePayload.coordinates[0][0]===store.lng&&routePayload.coordinates[0][1]===store.lat,'Freight requests a driving route from the configured store coordinates');
const profile={name:'Visitante Teste',cpf:'52998224725',phone:'11999999999',whatsappConsent:false,address};const input={guest:true,requestId:crypto.randomUUID(),expectedTotal:4088,items:[{id:productId,quantity:2}],profile,delivery:'delivery',quoteId,payment:'cash',change:5000,note:'Sem talheres <script>alert(1)</script>'};
r=await visitor.request('orders','POST',{...input,guest:false});ok(r.status===422,'Guest checkout requires explicit guest choice');
r=await bob.request('orders','POST',input);ok(r.status===422,'Another customer cannot use guest freight quote');
r=await visitor.request('orders','POST',{...input,expectedTotal:1});ok(r.status===409,'Tampered total cannot create order');
r=await visitor.request('orders','POST',{...input,profile:{...profile,address:{...address,number:'60'}}});ok(r.status===422,'Changing address invalidates route quote');
r=await visitor.request('orders','POST',{...input,profile:{...profile,address:{...address,location:{...address.location,lat:-23.551}}}});ok(r.status===422,'Changing the delivery pin invalidates the priced quote');
r=await visitor.request('orders','POST',input);ok(r.status===201&&r.order.total===4088,'Guest completes a valid delivery order without account');const guestOrder=r.order;
r=await visitor.request('orders','POST',input);ok(r.status===200&&r.order.id===guestOrder.id,'Guest order retry does not duplicate purchase');
r=await visitor.request('orders');ok(r.orders.length===1,'Guest can track the order in original browser');
r=await stranger.request('orders');ok(r.status===401,'Different browser cannot read guest history');
r=await bob.request('orders/'+guestOrder.id+'/print');ok(r.status===404,'Other account cannot print guest order');
r=await visitor.request('orders/'+guestOrder.id+'/print');ok(r.status===200&&r.html.includes('5,3 km')&&r.html.includes('&lt;script&gt;')&&!r.html.includes('<script>alert(1)</script>'),'Receipt includes actual route and escapes user text');
ok(!r.html.includes(profile.cpf),'Printed order excludes CPF');ok((r.html.match(/class="location-qr"/g)||[]).length===1&&r.html.indexOf('class="location-qr"')>r.html.indexOf('VIA DO ENTREGADOR'),'Location QR appears on courier copy');
ok(r.html.includes('VIA DO CLIENTE')&&r.html.includes('VIA DO ENTREGADOR')&&r.html.includes('RECORTE AQUI'),'Receipt has two detachable copies');
const qrLink=new URL(decodeQR(r.html));
ok(qrLink.hostname==='www.google.com'&&qrLink.searchParams.get('destination')==='-23.550321,-46.633112'&&qrLink.searchParams.get('dir_action')==='navigate','Independent QR decoder opens directions to confirmed exact coordinates');
ok(r.html.includes('COBRAR')&&r.html.includes('9,12')&&r.html.includes('Troco a devolver'),'Cash receipt tells courier how much to collect and return');

globalThis.__testUser={userId:'platform-owner',displayName:'Owner'};
r=await owner.request('orders/'+guestOrder.id+'/print');ok(r.status===200,'Authorized bakery owner can print guest order');
r=await owner.request('admin/categories','POST',{name:'Sobremesas'});ok(r.status===200,'Categories can be added');
r=await owner.request('admin/categories','DELETE',{name:'Brownies'});ok(r.status===422,'Removing used category does not destroy products');
r=await owner.request('admin/categories','DELETE',{name:'Sobremesas'});ok(r.status===200,'Unused category can be removed');
r=await owner.request('products/'+productId+'/comments','DELETE',{id:comment.id});ok(r.status===200,'Owner can moderate a customer comment');
globalThis.__testUser=null;
globalThis.fetch=async()=>Response.json({routes:[]});r=await visitor.request('quote','POST',address);ok(r.status===422,'No route does not fabricate a delivery price');
globalThis.fetch=async()=>Response.json({routes:[{summary:{distance:16000}}]});r=await visitor.request('quote','POST',address);ok(r.status===422,'Route beyond maximum delivery distance is rejected');
// Create a customer order and then exercise signed payment confirmation.
globalThis.fetch=async(url)=>String(url)==='https://api.mercadopago.com/checkout/preferences'?Response.json({init_point:'https://www.mercadopago.com.br/checkout/fixture'}):Promise.reject(Error('Unexpected request'));
r=await alice.request('orders','POST',{...input,guest:false,requestId:crypto.randomUUID(),expectedTotal:2800,delivery:'pickup',quoteId:undefined,payment:'card',profile:{...profile,address:undefined}});ok(r.status===201&&r.order.checkout_url,'Registered customer can use configured card checkout');const paidOrder=r.order;
r=await alice.request('orders');ok(r.orders.length===1&&r.orders[0].id===paidOrder.id,'Account history contains only that customer orders');
r=await bob.request('orders');ok(r.orders.length===0,'Second customer has an isolated history');
let amount=28;globalThis.fetch=async()=>Response.json({id:123,external_reference:paidOrder.id,currency_id:'BRL',transaction_amount:amount,status:'approved'});
const ts=String(Date.now()),requestId='fixture-webhook',key=await crypto.subtle.importKey('raw',new TextEncoder().encode('fixture-mp-signature'),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`id:123;request-id:${requestId};ts:${ts};`))),v=>v.toString(16).padStart(2,'0')).join('');
r=await stranger.request('webhooks/mercadopago?data.id=123','POST',{}, {'x-request-id':requestId,'x-signature':`ts=${ts},v1=${'0'.repeat(64)}`});ok(r.status===401,'Forged payment webhook rejected');
amount=1;r=await stranger.request('webhooks/mercadopago?data.id=123','POST',{}, {'x-request-id':requestId,'x-signature':`ts=${ts},v1=${signature}`});ok(r.status===409,'Wrong provider amount rejected');
amount=28;r=await stranger.request('webhooks/mercadopago?data.id=123','POST',{}, {'x-request-id':requestId,'x-signature':`ts=${ts},v1=${signature}`});ok(r.status===200&&sql.prepare('SELECT payment_status FROM orders WHERE id=?').get(paidOrder.id).payment_status==='Pago','Signed matching payment confirms order');
r=await alice.request('profile','PUT',profile,{Origin:'https://attacker.test'});ok(r.status===403,'Customer mutations reject cross-origin requests');
r=await stranger.request('customer/recover','POST',{email:'alice@example.test',recoveryCode:'a'.repeat(64),password:'Nova senha segura 123'});ok(r.status===401,'Wrong recovery code cannot reset password');
r=await stranger.request('customer/recover','POST',{email:'alice@example.test',recoveryCode:recovery,password:'Nova senha segura 123'});ok(r.status===200&&r.recoveryCode!==recovery,'Recovery code permits password reset and rotates recovery secret');
r=await alice.request('customer/session');ok(!r.signedIn,'Password reset revokes all old sessions');
r=await stranger.request('customer/recover','POST',{email:'alice@example.test',recoveryCode:recovery,password:'Outra senha segura 123'});ok(r.status===401,'Recovery code cannot be replayed');
r=await alice.request('customer/login','POST',{email:'alice@example.test',password:'Nova senha segura 123'});ok(r.status===200,'New password logs into the existing account');
r=await alice.request('orders');ok(r.orders[0].id===paidOrder.id,'Password recovery preserves order history');
for(let i=0;i<16;i++)r=await bob.request('customer/login','POST',{email:'bob@example.test',password:'wrong'});ok(r.status===429,'Authentication is rate limited');

// No provider credentials: card terminal and Pix key are real manual flows.
r=await alice.request('orders/'+paidOrder.id+'/print');ok(r.html.includes('PAGO · NÃO COBRAR')&&!r.html.includes('location-qr" href='),'Paid pickup receipt never charges again and has no customer-location QR');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/order','PATCH',{id:paidOrder.id,paid:true});ok(r.status===422,'Online card cannot be marked paid manually');
sql.prepare("DELETE FROM settings WHERE key='integrations'").run();
const manualStore={...store,cardOnDelivery:true,pixKey:'loja@example.test',pixName:'Loja Confeitaria',pixCity:'SAO PAULO'};
r=await owner.request('admin/settings','PUT',manualStore);ok(r.status===200,'Manual Pix and terminal configure without bank account credentials');
r=await owner.request('admin/whatsapp/manual','PUT',{phone:'5511988888888'});ok(r.status===200,'Owner saves WhatsApp shortcut number without a token');manualStore.whatsapp='5511988888888';
globalThis.__testUser=null;
r=await stranger.request('admin/whatsapp/manual','PUT',{phone:'5511977777777'});ok(r.status===401||r.status===403,'Public visitors cannot replace store WhatsApp');
let externalCalls=0;globalThis.fetch=async()=>{externalCalls++;throw Error('No external call allowed for manual checkout')};
r=await visitor.request('orders','POST',{...input,requestId:crypto.randomUUID(),payment:'card_machine'});ok(r.status===201&&r.order.data.paymentProvider==='manual'&&!r.order.checkout_url&&!r.paymentError&&r.order.payment_status==='Pagar na entrega'&&r.order.data.change===null,'Card without provider creates unpaid terminal order, never online checkout');const terminalOrder=r.order;
r=await visitor.request('orders/'+terminalOrder.id+'/pay','POST',{});ok(r.status===422,'Terminal order cannot open an online charge');
r=await visitor.request('orders/'+terminalOrder.id+'/print');ok(r.html.includes('LEVAR A MAQUININHA')&&r.html.includes('COBRAR')&&r.html.includes('Cartão na maquininha'),'Terminal receipt tells courier to bring the machine and collect');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/order','PATCH',{id:terminalOrder.id,status:'Em preparo'});ok(r.status===200,'Terminal order can enter preparation before collection');
r=await owner.request('admin/order','PATCH',{id:terminalOrder.id,paid:true});ok(r.status===200,'Owner confirms terminal payment after collection');
r=await owner.request('orders/'+terminalOrder.id+'/print');ok(r.html.includes('PAGO · NÃO COBRAR')&&!r.html.includes('LEVAR A MAQUININHA'),'Reprinted terminal order reflects paid status');
globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...input,requestId:crypto.randomUUID(),payment:'pix'});ok(r.status===201&&r.order.data.pixKey===manualStore.pixKey&&r.order.data.pixName===manualStore.pixName&&r.order.data.pixCode.includes('br.gov.bcb.pix')&&!r.order.checkout_url&&r.order.payment_status==='Aguardando pagamento','Manual Pix includes the store key and holder but remains unpaid');const pixOrder=r.order;
r=await visitor.request('orders/'+pixOrder.id+'/print');ok(r.html.includes('PIX · AGUARDA CONFERÊNCIA')&&r.html.includes('loja@example.test'),'Manual Pix print asks store to verify receipt');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/order','PATCH',{id:pixOrder.id,status:'Em preparo'});ok(r.status===422,'Manual Pix still requires confirmation before preparation');
r=await owner.request('admin/order','PATCH',{id:pixOrder.id,paid:true,status:'Em preparo'});ok(r.status===200,'Owner can confirm received Pix and start preparation');
r=await owner.request('admin/settings','PUT',{...manualStore,cardOnDelivery:false});ok(r.status===200,'Store may disable terminal payment');
globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...input,requestId:crypto.randomUUID(),payment:'card_machine'});ok(r.status===422,'Disabled terminal is enforced by server when no online provider exists');
r=await visitor.request('orders');ok(r.storeWhatsapp==='5511988888888','Guest can open a summary to the configured store number');
ok(externalCalls===0,'Manual checkout and locally generated QR do not contact payment, message or QR services');
// Verify the per-product metadata and token-free link encoding.
await esbuild.build({entryPoints:[path.resolve('lib/product-sharing.ts'),path.resolve('lib/order-display.ts'),path.resolve('lib/store-hours.ts')],bundle:true,platform:'node',format:'esm',outdir:dir,outExtension:{'.js':'.mjs'},logLevel:'silent'});
const sharing=await import(path.join(dir,'product-sharing.mjs')),display=await import(path.join(dir,'order-display.mjs'));
const meta=sharing.productMetadata({id:productId,name:'Brownie & amor',description:'Chocolate artesanal',price:1400,image:'/images/brownies.jpg'},origin);
ok(meta.openGraph.images[0].url===origin+'/images/brownies.jpg'&&meta.openGraph.url===origin+'/produto/brownie-amor--'+productId&&meta.twitter.card==='summary_large_image','Product link declares its own absolute image and rich social preview');
const wa=new URL(display.whatsappLink('5511988888888',display.orderMessage(terminalOrder),true));
ok(wa.hostname==='web.whatsapp.com'&&wa.searchParams.get('phone')==='5511988888888'&&wa.searchParams.get('text').includes('LEVAR A MAQUININHA'),'WhatsApp Web opens correct recipient with collection instructions ready to review');

// Node bridge protocol: isolated fixture only, no real WhatsApp authentication.
globalThis.__testUser=null;
r=await stranger.request('admin/whatsapp/bridge');ok(r.status===401||r.status===403,'Connection status and QR are restricted to bakery admin');
r=await stranger.request('admin/whatsapp/pairing','POST',{});ok(r.status===401||r.status===403,'Only owner can authorize a WhatsApp bridge');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/whatsapp/bridge');ok(!r.installed&&!r.connected,'Absent connector never displays a fake connected state');
r=await owner.request('admin/whatsapp/connect','POST',{});ok(r.status===422,'Connect clearly requires an installed bridge');
r=await owner.request('admin/whatsapp/pairing','POST',{});ok(r.status===200&&r.code.length===24,'Admin obtains expiring one-use bridge pairing code');const pairingCode=r.code;
globalThis.__testUser=null;
r=await stranger.request('bridge/pair','POST',{code:pairingCode},{Origin:''});ok(r.status===201&&r.token.length===64,'Connector redeems pairing code without a browser session');const bridgeToken=r.token;
ok(!sql.prepare('SELECT token_hash FROM whatsapp_bridge').get().token_hash.includes(bridgeToken),'Only the bridge credential hash is stored by site');
r=await stranger.request('bridge/pair','POST',{code:pairingCode},{Origin:''});ok(r.status===401,'Pairing code cannot be reused');
const runner=crypto.randomUUID(),bridgeHeaders={Authorization:'Bearer '+bridgeToken,Origin:''};
r=await stranger.request('bridge/heartbeat','POST',{runner,state:'ready'});ok(r.status===401,'Unpaired services cannot claim messages');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/settings','PUT',{...manualStore,whatsappEnabled:true,whatsappMode:'webjs'});ok(r.status===200,'Store chooses whatsapp-web.js for automatic summaries');
r=await owner.request('admin/whatsapp/connect','POST',{});ok(r.status===200&&r.desired==='connected','Connect queues command for the installed service');
globalThis.__testUser=null;
r=await stranger.request('bridge/heartbeat','POST',{runner,state:'qr',qr:'fixture-whatsapp-qr-only' },bridgeHeaders);ok(r.status===200&&r.desired==='connected'&&!r.job,'QR-stage connector cannot send queued summaries');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/whatsapp/bridge');ok(r.online&&!r.connected&&Buffer.from(r.qr.split(',')[1],'base64').toString().includes('endereço')&&decodeQR(Buffer.from(r.qr.split(',')[1],'base64').toString())==='fixture-whatsapp-qr-only','Panel receives an actual connector QR payload, privately rendered');
globalThis.__testUser=null;
const automaticInput={...input,requestId:crypto.randomUUID(),delivery:'pickup',expectedTotal:2800,quoteId:undefined,payment:'cash',profile:{...profile,address:undefined,whatsappConsent:true}};
r=await visitor.request('orders','POST',automaticInput);ok(r.status===201,'Order queues automatic summary without delaying its creation');const automaticOrder=r.order;
ok(sql.prepare('SELECT COUNT(*) AS n FROM whatsapp_outbox WHERE order_id=?').get(automaticOrder.id).n===2,'Consenting customer and bakery each have one queued summary');
r=await visitor.request('orders','POST',automaticInput);ok(sql.prepare('SELECT COUNT(*) AS n FROM whatsapp_outbox WHERE order_id=?').get(automaticOrder.id).n===2,'Repeated checkout never duplicates outbox jobs');
r=await visitor.request('orders','POST',{...automaticInput,requestId:crypto.randomUUID(),profile:{...automaticInput.profile,whatsappConsent:false}});ok(sql.prepare('SELECT COUNT(*) AS n FROM whatsapp_outbox WHERE order_id=?').get(r.order.id).n===1,'Without customer consent only bakery alert is queued');
r=await stranger.request('bridge/heartbeat','POST',{runner,state:'ready',phone:'5511977777777'},bridgeHeaders);ok(r.status===200&&r.job&&!r.job.resumed&&r.job.text.includes('Forma de pagamento')&&!r.job.text.includes(profile.cpf),'Ready bridge receives a single authorized summary with payment instructions');const firstJob=r.job;
r=await stranger.request('bridge/heartbeat','POST',{runner:crypto.randomUUID(),state:'ready'},bridgeHeaders);ok(r.status===409,'Second running bridge is rejected while leader lease is active');
r=await stranger.request('bridge/heartbeat','POST',{runner,state:'ready'},bridgeHeaders);ok(r.job.id===firstJob.id&&r.job.resumed,'Unacknowledged job resumes for journal reconciliation, not blind resend');
r=await stranger.request('bridge/result','POST',{id:firstJob.id,leaseToken:'0'.repeat(64),status:'sent',messageId:'fixture-id'},bridgeHeaders);ok(r.status===404,'Incorrect job claim cannot confirm another delivery');
r=await stranger.request('bridge/result','POST',{id:firstJob.id,leaseToken:firstJob.leaseToken,status:'sent'},bridgeHeaders);ok(r.status===422,'Sent status requires a WhatsApp message identifier');
const resultBody={id:firstJob.id,leaseToken:firstJob.leaseToken,status:'sent',messageId:'fixture-whatsapp-message'};
r=await stranger.request('bridge/result','POST',resultBody,bridgeHeaders);ok(r.status===200&&sql.prepare('SELECT status FROM notifications WHERE id=?').get(firstJob.id).status==='enviado','Message result updates the bakery order notification');
r=await stranger.request('bridge/result','POST',resultBody,bridgeHeaders);ok(r.status===200,'Repeated acknowledgement is idempotent');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/whatsapp/disconnect','POST',{});ok(r.desired==='disconnected'&&!r.qr,'Disconnect removes pairing QR and pauses dispatch');
globalThis.__testUser=null;
r=await stranger.request('bridge/heartbeat','POST',{runner,state:'ready'},bridgeHeaders);ok(!r.job&&r.desired==='disconnected','Disconnected mode never releases a new message');
globalThis.__testUser={userId:'platform-owner'};
sql.prepare('UPDATE whatsapp_bridge SET last_seen=?').run(Date.now()-40000);
r=await owner.request('admin/whatsapp/bridge');ok(!r.online&&!r.connected&&!r.qr,'Stale heartbeat cannot present a live session or QR');
globalThis.__testUser={userId:'platform-owner'};r=await owner.request('admin/settings','PUT',{...store,hoursMode:'closed'});ok(r.status===200,'Owner can close store');globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...input,requestId:crypto.randomUUID()});ok(r.status===422,'Server rejects new orders when closed');
// New panel login, date history, notification cursor and private quote attachments.
globalThis.__testUser=null;
r=await stranger.request('admin/accounts','POST',{name:'Intruso',login:'intruso',password});ok(r.status===401,'Public registration cannot create panel accounts');
globalThis.__testUser={userId:'platform-owner',displayName:'Owner'};
r=await owner.request('admin/accounts','POST',{name:'Atendimento',login:'Balcao',password:'curta'});ok(r.status===422,'Panel account requires a strong initial password');
r=await owner.request('admin/accounts','POST',{name:'Atendimento',login:'Balcao',password});ok(r.status===201,'Bound owner creates a named panel login');
r=await owner.request('admin/accounts');const account=r.accounts[0];ok(account.login==='balcao'&&!JSON.stringify(r).includes('password_hash'),'Access listing normalizes login and never returns password hashes');
globalThis.__testUser=null;const staff=client('10.0.1.1');
r=await staff.request('admin/login','POST',{login:'balcao',password:'incorreta'});ok(r.status===401,'Wrong panel password is rejected');
r=await staff.request('admin/login','POST',{login:'BALCAO',password});ok(r.status===200&&r.headers.get('set-cookie').includes('__Host-cca_admin')&&r.headers.get('set-cookie').includes('HttpOnly'),'Staff logs in independently with a secure panel cookie');
r=await staff.request('session');ok(r.isAdmin&&!r.owner,'Panel identifies staff separately from responsible owner');
r=await staff.request('admin/data');ok(r.status===200&&r.stats&&Number.isInteger(r.cursor),'Password login grants persisted orders and exact aggregate metrics');let feedCursor=r.cursor;
r=await staff.request('orders/'+guestOrder.id+'/print');ok(r.status===200&&r.html.includes('VIA DO ENTREGADOR'),'Staff can print the real courier receipt through password authentication');
r=await staff.request('admin/accounts','POST',{name:'Escalada',login:'escala',password});ok(r.status===403,'Staff cannot grant new privileged access');
r=await alice.request('admin/history');ok(r.status===401,'Customer account cannot read administrative history');
r=await staff.request('admin/history?from=2026-09-16&to=2026-09-15');ok(r.status===422,'History rejects inverted date range');
r=await staff.request('admin/history?from=2026-02-30');ok(r.status===422,'History rejects nonexistent calendar date');
const historyFixture={...guestOrder,data:JSON.stringify(guestOrder.data)};
function fixtureOrder(date,status='Concluído'){const id=crypto.randomUUID();sql.prepare('INSERT INTO orders(id,user_id,request_id,code,data,total,status,payment,payment_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,'history-fixture',crypto.randomUUID(),id.slice(0,8),historyFixture.data,1000,status,'cash','Pago',Date.parse(date));return id}
const insideStart=fixtureOrder('2005-05-10T03:00:00Z'),insideEnd=fixtureOrder('2005-05-11T02:59:59Z','Cancelado');fixtureOrder('2005-05-10T02:59:59Z');fixtureOrder('2005-05-11T03:00:00Z');
r=await staff.request('admin/history?from=2005-05-10&to=2005-05-10');ok(r.total===2&&r.orders.some(o=>o.id===insideStart)&&r.orders.some(o=>o.id===insideEnd),'Inclusive date filter respects both midnight boundaries in store timezone');
r=await staff.request('admin/history?from=2005-05-10&to=2005-05-10&status=Cancelado');ok(r.total===1&&r.orders[0].status==='Cancelado','Status and date filters combine in persisted query');
for(let n=0;n<205;n++)fixtureOrder('2006-01-01T12:00:00Z');
r=await staff.request('admin/history?from=2006-01-01&to=2006-01-01&page=6');ok(r.total===205&&r.orders.length===5&&r.pages===6,'History reaches records beyond former 200-order limit');
r=await staff.request('admin/data');feedCursor=r.cursor;
r=await staff.request('admin/order-feed?after='+feedCursor);ok(r.newCount===0,'Opening a loaded panel does not alert for existing orders');
const alertOrder=fixtureOrder(new Date().toISOString(),'Recebido');
r=await staff.request('admin/order-feed?after='+feedCursor);ok(r.newCount===1,'A newly persisted order advances the notification cursor');feedCursor=r.cursor;
sql.prepare('UPDATE orders SET status=? WHERE id=?').run('Em preparo',alertOrder);
r=await staff.request('admin/order-feed?after='+feedCursor);ok(r.newCount===0,'Polling and status updates do not repeat the new-order sound');
r=await staff.request('admin/password','PUT',{currentPassword:'errada',password:'Outra senha segura 123'});ok(r.status===403,'Password change requires the current staff password');
r=await staff.request('admin/password','PUT',{currentPassword:password,password:'Outra senha segura 123'});ok(r.status===200&&r.signInAgain,'Staff can change own password');
r=await staff.request('admin/data');ok(r.status===401,'Password change revokes earlier panel sessions');
r=await staff.request('admin/login','POST',{login:'balcao',password:'Outra senha segura 123'});ok(r.status===200,'New panel password restores access');
// Same application endpoint receives real multipart bytes; R2 is isolated in memory.
async function multipart(actor,endpoint,file){const body=new FormData();body.append('file',file);if(endpoint==='budget-photos')body.append('original',file);return route.POST(new Request(origin+'/api/'+endpoint,{method:'POST',headers:{Origin:origin,'cf-connecting-ip':'10.0.2.1',Cookie:[...actor.jar].map(([k,v])=>k+'='+v).join('; ')},body}))}
const png=new File([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5S8AAAAASUVORK5CYII=','base64')],'reference.png',{type:'image/png'});
let response=await multipart(visitor,'budget-photos',png);r=await response.json();ok(response.status===201&&r.id&&r.url,'Guest uploads a reference photo into private storage');const photoId=r.id;
r=await stranger.request('budget-images/'+photoId);ok(r.status===401,'Anonymous visitors cannot open an uploaded reference');
r=await bob.request('budget-images/'+photoId);ok(r.status===404,'Other customer cannot read a reference image');
r=await visitor.request('budget-images/'+photoId);ok(r.status===200&&r.headers.get('cache-control')==='private,no-store','Uploading customer can access photo without a public cache');
const budget={requestId:crypto.randomUUID(),name:'Cliente festa',phone:'11999999999',date:'2099-12-20',cake:true,slices:20,sweets:true,quantity:100,description:'Bolo de chocolate e 50 brigadeiros, 50 beijinhos.',photos:[photoId]};
r=await visitor.request('budgets','POST',{...budget,slices:15});ok(r.status===422,'Quote rejects cake sizes outside 12, 20 and 30 slices');
r=await visitor.request('budgets','POST',{...budget,quantity:99});ok(r.status===422,'Quote enforces a minimum of 100 sweets');
r=await visitor.request('budgets','POST',{...budget,date:'2020-01-01'});ok(r.status===422,'Quote rejects event dates in the past');
r=await bob.request('budgets','POST',budget);ok(r.status===422,'Another customer cannot attach a private reference to their quote');
r=await visitor.request('budgets','POST',budget);ok(r.status===201&&r.budget.status==='Recebido'&&!r.budget.total,'Quote is recorded separately without charging or creating a delivery order');const budgetId=r.budget.id;
r=await visitor.request('budgets','POST',budget);ok(r.status===200&&r.budget.id===budgetId,'Retrying a quote request does not duplicate it');
r=await visitor.request('budget-photos','DELETE',{id:photoId});ok(r.status===404,'Submitted reference cannot be removed from the recorded quote');
r=await bob.request('budgets');ok(!r.budgets.some(b=>b.id===budgetId),'Quote history is isolated by customer or guest session');
r=await staff.request('admin/budgets');ok(r.budgets.some(b=>b.id===budgetId),'Password-authenticated staff can receive quote requests');
r=await staff.request('budget-images/'+photoId);ok(r.status===200,'Authorized staff can see reference images');
r=await staff.request('admin/budgets','PATCH',{id:budgetId,status:'Em análise'});ok(r.status===200,'Staff updates quote workflow');
r=await visitor.request('budgets');ok(r.budgets[0].status==='Em análise','Customer sees persisted quote status');
globalThis.__testUser={userId:'platform-owner'};
response=await multipart(owner,'admin/upload',new File(['<svg onload="alert(1)"/>'],'bad.png',{type:'image/png'}));ok(response.status===422,'Photo upload rejects executable content with an image filename');
response=await multipart(owner,'admin/upload',new File([new Uint8Array(1600000)],'large.jpg',{type:'image/jpeg'}));ok([413,422].includes(response.status),'Upload enforces the optimized image size limit');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/accounts','DELETE',{id:account.id});ok(r.status===200,'Responsible owner can revoke a panel login');
globalThis.__testUser=null;r=await staff.request('admin/data');ok(r.status===401,'Removing an account revokes its open sessions');
ok(sharing.productIdFromPath('brownie-amor--'+productId)===productId&&sharing.productIdFromPath(productId)===productId,'Named product links preserve old product IDs');

// New delivery/pickup, native Pix, least privilege and reporting behavior.
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/settings','PUT',{...manualStore,paymentProvider:'infinitepay',pickupPrepaid:true});ok(r.status===422,'Prepaid-only pickup cannot be enabled without an online provider');
r=await owner.request('admin/integrations','PUT',{infiniteTag:'fixture-bakery'});ok(r.status===200,'InfinitePay can be configured with a merchant tag');
r=await owner.request('admin/settings','PUT',{...manualStore,paymentProvider:'infinitepay',pickupPrepaid:true});ok(r.status===200,'Merchant can require online prepayment for pickup');
globalThis.__testUser=null;
const pickup={...input,requestId:crypto.randomUUID(),delivery:'pickup',quoteId:undefined,expectedTotal:2800,profile:{...profile,cpf:'',email:'',address:undefined},payment:'cash'};
r=await visitor.request('orders','POST',pickup);ok(r.status===422,'Server rejects cash pickup when prepayment is required');
globalThis.__testUser={userId:'platform-owner'};await owner.request('admin/settings','PUT',{...manualStore,paymentProvider:'infinitepay',pickupPrepaid:false});globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...pickup,payment:'card_machine'});ok(r.status===201&&r.order.data.fee===0&&r.order.payment_status==='Pagar na retirada'&&!r.order.data.address,'Pickup with online provider still supports maquininha and needs no address or CPF');const collected=r.order;
r=await stranger.request('tracking/'+collected.data.trackingToken);ok(r.status==='Recebido'&&r.code===collected.code&&!r.profile&&!r.address,'Private tracking link exposes only the order summary');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/order','PATCH',{id:collected.id,status:'Retirado',pickupCode:collected.data.pickupCode});ok(r.status===422,'Pickup cannot skip preparation and confirmation');
await owner.request('admin/order','PATCH',{id:collected.id,status:'Em preparo'});await owner.request('admin/order','PATCH',{id:collected.id,status:'Pronto para retirada'});
r=await owner.request('admin/order','PATCH',{id:collected.id,status:'Retirado',pickupCode:collected.data.pickupCode});ok(r.status===422,'Unpaid pickup cannot be marked collected');
await owner.request('admin/order','PATCH',{id:collected.id,paid:true});await owner.request('admin/order','PATCH',{id:collected.id,paid:true});
r=await owner.request('admin/order','PATCH',{id:collected.id,status:'Retirado',pickupCode:'wrong'});ok(r.status===422,'Pickup validates the customer collection code');
r=await owner.request('admin/order','PATCH',{id:collected.id,status:'Retirado',pickupCode:collected.data.pickupCode});ok(r.status===200,'Paid ready pickup can be collected with the correct code');
ok(sql.prepare("SELECT COUNT(*) n FROM order_events WHERE order_id=? AND event='Pago'").get(collected.id).n===1,'Repeated payment confirmation records one event');
r=await owner.request('admin/history?delivery=pickup&payment=card_machine&paymentStatus=Pago');ok(r.orders.some(o=>o.id===collected.id)&&r.orders.every(o=>o.data.delivery==='pickup'&&o.payment==='card_machine')&&r.metrics.paid>=2800,'History combines delivery, method and payment filters with totals');
r=await owner.request('admin/history?delivery=pickup&export=1');ok(r.status===200&&r.headers.get('content-type').includes('text/csv')&&r.html.includes(collected.code),'History export returns filtered CSV');
r=await owner.request('admin/customers?q=Visitante');ok(r.customers.length>0&&r.customers.every(c=>c.data.name.includes('Visitante')),'Customer management includes guest purchase profiles');
r=await owner.request('admin/accounts','POST',{name:'Produção',login:'producao',password,role:'production'});ok(r.status===201,'Owner creates production-only access');globalThis.__testUser=null;
const cook=client('10.0.3.1');await cook.request('admin/login','POST',{login:'producao',password});
r=await cook.request('admin/settings','PUT',manualStore);ok(r.status===403,'Production role cannot change store settings');r=await cook.request('admin/customers');ok(r.status===403,'Production role cannot query customer management');r=await cook.request('admin/order','PATCH',{id:collected.id,paid:true});ok(r.status===403,'Production cannot confirm money received');
globalThis.__testUser={userId:'platform-owner'};await owner.request('admin/integrations','PUT',{mpToken:'fixture-mp-token',mpWebhookSecret:'fixture-mp-signature'});await owner.request('admin/settings','PUT',{...manualStore,paymentProvider:'mercadopago',whatsappEnabled:false});globalThis.__testUser=null;
let nativeAmount=2800,nativeOrderId='',pixCreates=0;
globalThis.fetch=async(url,options)=>{if(String(url)==='https://api.mercadopago.com/v1/payments'){const b=JSON.parse(options.body);nativeOrderId=b.external_reference;pixCreates++;return Response.json({id:777,status:'pending',point_of_interaction:{transaction_data:{qr_code:'000201-fixture-pix'}}})}if(String(url).endsWith('/v1/payments/777'))return Response.json({id:777,external_reference:nativeOrderId,transaction_amount:nativeAmount/100,currency_id:'BRL',status:'approved'});throw Error('Unexpected provider request')};
r=await visitor.request('orders','POST',{...pickup,requestId:crypto.randomUUID(),payment:'pix',profile:{...pickup.profile,cpf:'52998224725',email:'checkout@example.test'}});ok(r.status===201&&r.order.data.pixCode&&!r.order.checkout_url,'Mercado Pago Pix is generated inside the site');const nativeOrder=r.order;
await visitor.request('orders/'+nativeOrder.id+'/pay','POST',{});ok(pixCreates===1,'Retrying native Pix reuses the same saved charge');
nativeAmount=100;r=await visitor.request('orders/'+nativeOrder.id+'/check','POST',{});ok(r.order.payment_status!=='Pago','Native Pix amount mismatch cannot confirm payment');nativeAmount=2800;
r=await visitor.request('orders/'+nativeOrder.id+'/check','POST',{});ok(r.order.payment_status==='Pago','Native Pix checks provider amount currency and order before confirmation');
globalThis.__testUser={userId:'platform-owner'};sql.prepare("DELETE FROM settings WHERE key='integrations'").run();await owner.request('admin/settings','PUT',{...manualStore,whatsappEnabled:false});globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...pickup,requestId:crypto.randomUUID(),payment:'pix'});const proofOrder=r.order;response=await multipart(visitor,'orders/'+proofOrder.id+'/proof',png);ok(response.status===200&&sql.prepare('SELECT payment_status FROM orders WHERE id=?').get(proofOrder.id).payment_status==='Comprovante em análise','Pix proof upload requests review without marking paid');
const proof=sql.prepare('SELECT id FROM order_proofs WHERE order_id=?').get(proofOrder.id);r=await bob.request('admin/proofs/'+proof.id);ok(r.status===401,'Proof image is not public');
globalThis.__testUser={userId:'platform-owner'};
const uploadBody=new FormData();uploadBody.append('file',png);uploadBody.append('original',png);response=await route.POST(new Request(origin+'/api/admin/upload',{method:'POST',headers:{Origin:origin},body:uploadBody}));r=await response.json();const originalId=r.url.split('/').pop().split('.')[0];ok(response.status===200&&sql.prepare('SELECT id FROM image_originals WHERE id=?').get(originalId),'Product upload preserves original privately while publishing optimized image');

const hoursModule=await import(path.join(dir,'store-hours.mjs'));
const weekly=hoursModule.defaultHours.map(h=>({...h,enabled:true,open:'09:00',close:'18:00',breakStart:'12:00',breakEnd:'13:00'}));
ok(!hoursModule.businessStatus({open:true,hoursMode:'auto',hours:weekly,timezone:'America/Sao_Paulo'},new Date('2026-09-17T15:30:00Z')).open,'Store blocks checkout during configured lunch interval');
ok(!hoursModule.businessStatus({open:true,hoursMode:'auto',hours:weekly,exceptions:[{date:'2026-09-17',closed:true}],timezone:'America/Sao_Paulo'},new Date('2026-09-17T14:00:00Z')).open,'Scheduled closure date overrides regular opening hours');
globalThis.__testUser={userId:'platform-owner'};await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal',price:1400,category:'Brownies',image:'/images/brownies.jpg',active:true,sold_out:true});globalThis.__testUser=null;
r=await visitor.request('orders','POST',{...pickup,requestId:crypto.randomUUID()});ok(r.status===422,'Sold out products cannot be ordered even with a previously filled cart');
// Completion workflows: isolated data, real SQL guards and actual authorization routes.
sql.prepare('DELETE FROM auth_limits').run();
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal',price:1600,category:'Brownies',image:'/images/brownies.jpg',active:true,stock:2});ok(r.status===200,'Inventory quantity and price can be updated');
r=await owner.request('admin/categories','PATCH',{name:'Brownies',newName:'Brownies da casa'});ok(r.status===200&&sql.prepare('SELECT category FROM products WHERE id=?').get(productId).category==='Brownies da casa','Category rename updates catalog without rewriting order snapshots');
let catalogNow=await owner.request('catalog');
r=await owner.request('admin/categories','PATCH',{order:[...catalogNow.categories].reverse()});ok(r.status===200,'Category ordering is persisted');
const allProducts=(await owner.request('admin/data')).products.map(p=>p.id).reverse();r=await owner.request('admin/product-order','PUT',{ids:allProducts});ok(r.status===200&&(await owner.request('admin/data')).products[0].id===allProducts[0],'Product order follows the saved sequence');
r=await owner.request('admin/product-order','PUT',{ids:[productId]});ok(r.status===409,'Stale product ordering cannot silently drop catalog entries');
globalThis.__testUser=null;
r=await visitor.request('orders/'+guestOrder.id+'/repeat');ok(r.status===200&&r.items[0].quantity===2&&r.changes.some(x=>x.includes('preço')),'Repeat purchase reviews current price and inventory');
r=await bob.request('orders/'+guestOrder.id+'/repeat');ok(r.status===404,'Repeat cannot disclose another shopper order');
const stockInput={...pickup,requestId:crypto.randomUUID(),items:[{id:productId,quantity:2,note:'Embalar separado'}],expectedTotal:3200,payment:'cash'};
r=await visitor.request('orders','POST',stockInput);ok(r.status===201&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===0,'Order insertion atomically reserves available inventory');const stockOrder=r.order;
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal atualizado',price:1600,category:'Brownies da casa',image:'/images/brownies.jpg',active:true,stock:2,expectedStock:2});ok(r.status===200&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===0,'Editing product details does not overwrite inventory reserved since the editor opened');
r=await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal atualizado',price:1600,category:'Brownies da casa',image:'/images/brownies.jpg',active:true,stock:10,expectedStock:2});ok(r.status===409,'Stale manual inventory adjustment requires a fresh quantity');
globalThis.__testUser=null;
r=await visitor.request('orders','POST',stockInput);ok(r.status===200&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===0,'Order replay never reserves inventory twice');
r=await visitor.request('orders','POST',{...stockInput,requestId:crypto.randomUUID()});ok(r.status===422,'A second purchase cannot oversell exhausted stock');
r=await visitor.request('orders/'+stockOrder.id+'/print');ok(r.html.includes('Embalar separado'),'Per-item instructions reach both print copies');
globalThis.__testUser={userId:'platform-owner'};
await owner.request('admin/order','PATCH',{id:stockOrder.id,status:'Cancelado'});await owner.request('admin/order','PATCH',{id:stockOrder.id,status:'Cancelado'});ok(sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===2,'Cancel before preparation restores inventory exactly once');
const rules={delivery:{cash:true,card_machine:true,pix:true,card:true},pickup:{cash:false,card_machine:true,pix:true,card:true}};
r=await owner.request('admin/settings','PUT',{...manualStore,paymentRules:rules});ok(r.status===200,'Payment choices can be configured independently for pickup');
globalThis.__testUser=null;r=await visitor.request('orders','POST',{...stockInput,requestId:crypto.randomUUID()});ok(r.status===422,'Pickup-specific payment rule is enforced on server');
globalThis.__testUser={userId:'platform-owner'};await owner.request('admin/settings','PUT',{...manualStore,paymentRules:{...rules,pickup:{...rules.pickup,cash:true}},logo:'/brand-transparent.png',favicon:'/avatar.jpg',name:'Confeitando com Amor',budgetWhenClosed:true});
r=await owner.request('admin/budgets','PATCH',{id:budgetId,offer:{total:20000,fee:0,deposit:6000,expires:'2099-12-20',terms:'Sinal de R$ 60,00; restante antes da retirada.'}});ok(r.status===200,'Staff can issue a priced offer with deposit and expiry');
globalThis.__testUser=null;let quoted=(await visitor.request('budgets')).budgets.find(b=>b.id===budgetId),offer=quoted.data.offer;
r=await bob.request('budgets/'+budgetId+'/answer','POST',{version:offer.version,accept:true,payment:'cash'});ok(r.status===404,'Another customer cannot approve a quote');
r=await visitor.request('budgets/'+budgetId+'/answer','POST',{version:crypto.randomUUID(),accept:true,payment:'cash'});ok(r.status===409,'Old or forged offer version cannot create an order');
r=await visitor.request('budgets/'+budgetId+'/answer','POST',{version:offer.version,accept:true,payment:'cash'});ok(r.status===201&&r.order.total===20000&&r.order.data.depositRequired===6000&&r.order.data.budgetId===budgetId,'Customer acceptance creates the order with the exact agreed amount and deposit');const agreedOrder=r.order;
r=await visitor.request('budgets/'+budgetId+'/answer','POST',{version:offer.version,accept:true,payment:'cash'});ok(r.status===200&&r.order.id===agreedOrder.id,'Repeated acceptance does not duplicate the order');
globalThis.__testUser={userId:'platform-owner'};
r=await owner.request('admin/budgets','PATCH',{id:budgetId,offer:{...offer,total:1000}});ok(r.status===422,'Converted quote cannot change the accepted price');
r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,status:'Em preparo'});ok(r.status===422,'Preparation waits for the agreed deposit, even for cash');
let manualReceiptId=crypto.randomUUID();r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,paid:true,amount:6000,requestId:manualReceiptId});ok(r.status===200,'Partial deposit is recorded as an actual receipt');
r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,paid:true,amount:6000,requestId:manualReceiptId});ok(r.status===200&&sql.prepare('SELECT received,payment_status FROM orders WHERE id=?').get(agreedOrder.id).received===6000,'Receipt retry cannot duplicate a deposit');
r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,paid:true,amount:15000,requestId:crypto.randomUUID()});ok(r.status===422,'Receipt cannot exceed remaining balance');
r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,status:'Em preparo'});ok(r.status===200,'Confirmed deposit releases budget production');
r=await owner.request('orders/'+agreedOrder.id+'/print?paper=a4');ok(r.html.includes('140,00')&&r.html.includes('60,00')&&r.html.includes('class="a4"'),'Print shows actual deposit and remaining collection amount');
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
sql.prepare('UPDATE orders SET created_at=? WHERE id=?').run(Date.parse('2020-01-01T12:00:00Z'),agreedOrder.id);
r=await owner.request('admin/history?dateBasis=receipt&from='+today+'&to='+today+'&search='+agreedOrder.code);ok(r.status===200&&r.metrics.paid===6000&&r.orders[0].id===agreedOrder.id,'Receipt-date filter includes a payment for an older order');
r=await owner.request('admin/history?dateBasis=order&from='+today+'&to='+today+'&search='+agreedOrder.code);ok(r.total===0,'Order-date filter remains independent from receipt date');
let refundRequest=crypto.randomUUID();r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,refund:true,amount:1000,requestId:refundRequest});ok(r.status===200,'A partial manual deposit can be partially refunded without inventing the unpaid balance');
r=await owner.request('admin/order','PATCH',{id:agreedOrder.id,refund:true,amount:1000,requestId:refundRequest});ok(r.status===200&&sql.prepare('SELECT received FROM orders WHERE id=?').get(agreedOrder.id).received===5000,'Manual refund replay cannot return the same money twice');
r=await owner.request('admin/history?dateBasis=receipt&search='+agreedOrder.code);ok(r.metrics.paid===6000&&r.metrics.refunded===1000&&r.metrics.net===5000,'Reports separate gross receipts, refunds and actual net receipts');
const customerId=guestOrder.user_id;r=await owner.request('admin/customers','PATCH',{id:customerId,notes:'Preferência de atendimento'});ok(r.status===200,'Attendance notes are stored separately from customer profile');
globalThis.__testUser=null;r=await visitor.request('profile');ok(!JSON.stringify(r).includes('Preferência de atendimento'),'Internal notes never enter the customer profile response');
globalThis.__testUser={userId:'platform-owner'};const cookAccount=(await owner.request('admin/accounts')).accounts.find(a=>a.login==='producao');await owner.request('admin/accounts','PATCH',{...cookAccount,name:'Produção editada',active:false});globalThis.__testUser=null;
r=await cook.request('admin/data');ok(r.status===401,'Deactivating staff revokes existing sessions immediately');r=await cook.request('admin/login','POST',{login:'producao',password});ok(r.status===401,'Deactivated login cannot sign back in');
// Card Brick boundary uses tokens only; provider transport stays mocked.
globalThis.__testUser={userId:'platform-owner'};
await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal',price:1400,category:'Brownies da casa',image:'/images/brownies.jpg',active:true,stock:null});
await owner.request('admin/integrations','PUT',{mpToken:'fixture-mp-token',mpWebhookSecret:'fixture-mp-signature',mpPublicKey:'APP-USR-fixture-public'});await owner.request('admin/settings','PUT',{...manualStore,paymentProvider:'mercadopago'});globalThis.__testUser=null;
let cardPosts=0,cardPayload,cardHeader;const cardId=888;
globalThis.fetch=async(url,opts={})=>{if(String(url).endsWith('/v1/payments')&&opts.method==='POST'){cardPosts++;cardPayload=JSON.parse(opts.body);cardHeader=opts.headers['X-Idempotency-Key'];return Response.json({id:cardId,status:'approved',external_reference:cardPayload.external_reference,currency_id:'BRL',transaction_amount:cardPayload.transaction_amount,payment_type_id:'credit_card'})}if(String(url).endsWith('/v1/payments/888'))return Response.json({id:888,status:'approved',external_reference:cardPayload.external_reference,currency_id:'BRL',transaction_amount:28,payment_type_id:'credit_card'});throw Error('Unexpected test payment request '+url)};
r=await visitor.request('orders','POST',{...pickup,requestId:crypto.randomUUID(),payment:'card'});ok(r.status===201&&r.order.data.embeddedCard&&!r.order.checkout_url&&cardPosts===0,'Embedded card stages an unpaid order without any charge or redirect');const cardOrder=r.order;
r=await visitor.request('orders/'+cardOrder.id+'/card-config');ok(r.status===200&&r.amount===28&&r.publicKey==='APP-USR-fixture-public'&&!JSON.stringify(r).includes('fixture-mp-token'),'Card initialization reveals public key and server-calculated amount only');
r=await bob.request('orders/'+cardOrder.id+'/card-config');ok(r.status===404,'Card setup is restricted to the order owner');
const tokenized={token:'test_token_123456789012345678901234',installments:1,payment_method_id:'visa',issuer_id:'25',payer:{email:'card@example.test',identification:{type:'CPF',number:'52998224725'}}};
r=await visitor.request('orders/'+cardOrder.id+'/card','POST',{...tokenized,transaction_amount:0.01,card_number:'4111111111111111'});ok(r.status===422&&cardPosts===0,'Card endpoint rejects client totals and raw card fields');
r=await visitor.request('orders/'+cardOrder.id+'/card','POST',tokenized);ok(r.status==='approved'&&cardPosts===1&&cardPayload.transaction_amount===28&&cardPayload.three_d_secure_mode==='optional'&&/^[a-f0-9-]{36}$/.test(cardHeader),'Card amount comes from saved order, 3DS is enabled and provider call is idempotent');
await visitor.request('orders/'+cardOrder.id+'/card','POST',tokenized);ok(cardPosts===1&&sql.prepare('SELECT received FROM orders WHERE id=?').get(cardOrder.id).received===2800,'Repeated card submission cannot issue a second charge or duplicate a receipt');
ok(!sql.prepare('SELECT token_hash FROM card_attempts WHERE order_id=?').get(cardOrder.id).token_hash.includes(tokenized.token),'Card payment token is not retained in database');

// Expired Pix is renewed only after the bank confirms expiry.
sql.prepare('DELETE FROM auth_limits').run();let pixCount=0,pixData,pixPaymentId=900;
globalThis.fetch=async(url,opts={})=>{if(String(url).endsWith('/v1/payments')&&opts.method==='POST'){pixCount++;pixData=JSON.parse(opts.body);return Response.json({id:++pixPaymentId,status:'pending',point_of_interaction:{transaction_data:{qr_code:'000201-renewed-'+pixCount}}})}if(String(url).includes('/v1/payments/'))return Response.json({id:pixPaymentId,status:'cancelled',external_reference:pixData.external_reference,currency_id:'BRL',transaction_amount:28});throw Error('Unexpected test request '+url)};
r=await visitor.request('orders','POST',{...pickup,requestId:crypto.randomUUID(),payment:'pix',profile:{...pickup.profile,email:'pix@example.test',cpf:'52998224725'}});const expiring=r.order;
sql.prepare("UPDATE orders SET data=json_set(data,'$.pixExpires',?) WHERE id=?").run(Date.now()-10000,expiring.id);
r=await visitor.request('orders/'+expiring.id+'/pay','POST',{});ok(r.status===200&&pixCount===2&&r.order.data.pixGeneration&&r.order.data.pixCode==='000201-renewed-2','Confirmed expired Pix can be regenerated on the same order');
await visitor.request('orders/'+expiring.id+'/pay','POST',{});ok(pixCount===2,'Repeated request for renewed Pix reuses the new saved code');

// Force writes between preflight reads and the atomic batch, as a second
// request could do on D1. Failed guards must roll back all local changes.
sql.prepare('DELETE FROM auth_limits').run();
globalThis.__testUser={userId:'platform-owner'};
await owner.request('admin/product','POST',{id:productId,name:'Brownie',description:'Chocolate artesanal',price:1400,category:'Brownies da casa',image:'/images/brownies.jpg',active:true,stock:2});
globalThis.__testUser=null;
const racingInput={...pickup,payment:'cash',requestId:crypto.randomUUID()};
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('stock:'))){beforeBatch=null;sql.prepare('UPDATE products SET stock=1 WHERE id=?').run(productId)}};
r=await visitor.request('orders','POST',racingInput);
ok(r.status===409&&!sql.prepare('SELECT id FROM orders WHERE request_id=?').get(racingInput.requestId)&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===1,'Concurrent inventory change rolls back the complete new order');
sql.prepare('UPDATE products SET stock=2 WHERE id=?').run(productId);
r=await visitor.request('orders','POST',{...racingInput,requestId:crypto.randomUUID()});const racingOrder=r.order;
globalThis.__testUser={userId:'platform-owner'};
function concurrentReceipt(receiptId,amount){
 sql.prepare('INSERT INTO payment_receipts(id,order_id,amount,kind,method,provider,actor,occurred_at) VALUES(?,?,?,?,?,?,?,?)').run(receiptId,racingOrder.id,amount,amount>0?'payment':'refund','cash','manual','concurrent-fixture',Date.now());
 sql.prepare("UPDATE orders SET received=received+?,payment_status=?,paid_at=? WHERE id=?").run(amount,amount>0?'Parcialmente pago':'Estorno parcial',Date.now(),racingOrder.id);
}
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('receipt:'))){beforeBatch=null;concurrentReceipt('concurrent-payment',1000)}};
r=await owner.request('admin/order','PATCH',{id:racingOrder.id,paid:true,amount:2000,requestId:crypto.randomUUID()});
ok(r.status===409&&sql.prepare('SELECT received FROM orders WHERE id=?').get(racingOrder.id).received===1000&&sql.prepare('SELECT COUNT(*) n FROM payment_receipts WHERE order_id=?').get(racingOrder.id).n===1,'Concurrent receipt cannot overcollect or leave a detached ledger entry');
const replayPaymentId=crypto.randomUUID();
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('receipt:'))){beforeBatch=null;concurrentReceipt(racingOrder.id+':manual:'+replayPaymentId,500)}};
r=await owner.request('admin/order','PATCH',{id:racingOrder.id,paid:true,amount:500,requestId:replayPaymentId});
ok(r.status===200&&sql.prepare('SELECT received FROM orders WHERE id=?').get(racingOrder.id).received===1500,'Concurrent replay of the same receipt remains idempotent');
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('receipt:'))){beforeBatch=null;concurrentReceipt('concurrent-refund',-1000)}};
r=await owner.request('admin/order','PATCH',{id:racingOrder.id,refund:true,amount:1000,requestId:crypto.randomUUID()});
ok(r.status===409&&sql.prepare('SELECT received FROM orders WHERE id=?').get(racingOrder.id).received===500&&sql.prepare('SELECT COUNT(*) n FROM payment_receipts WHERE order_id=?').get(racingOrder.id).n===3,'Concurrent refund cannot return more than the received balance');
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('stage:'))){beforeBatch=null;sql.prepare("UPDATE orders SET status='Em preparo' WHERE id=?").run(racingOrder.id)}};
r=await owner.request('admin/order','PATCH',{id:racingOrder.id,status:'Cancelado'});
ok(r.status===409&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===0,'Preparation started concurrently prevents stale cancellation from restoring stock');
r=await owner.request('admin/order','PATCH',{id:racingOrder.id,status:'Cancelado'});
ok(r.status===200&&sql.prepare('SELECT stock FROM products WHERE id=?').get(productId).stock===0,'Canceling after preparation leaves prepared stock out of the catalog');
ok(sql.prepare('SELECT COUNT(*) n FROM commerce_guards').get().n===0,'Successful and rejected batches leave no pending transaction guards');

// First access by an owner-issued, expiring, one-use code. No live secrets.
const platformOwnerBefore=sql.prepare("SELECT value FROM settings WHERE key='admin'").get().value;
sql.prepare('DELETE FROM admin_sessions').run();sql.prepare('DELETE FROM admin_accounts').run();sql.prepare('DELETE FROM auth_limits').run();globalThis.__testUser=null;
const activation=client('10.0.1.1'),activationCode='AMOR-1234-ABCD-5678-EFAB-9012-CDEF';
const activationHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(activationCode.replaceAll('-','')))),v=>v.toString(16).padStart(2,'0')).join('');
const activationBody={code:activationCode,name:'Responsável de teste',login:'nova.admin',password};
r=await activation.request('admin/activate','POST',activationBody);ok(r.status===403,'First access is unavailable without an explicitly configured code');
globalThis.__testEnv.ADMIN_ACTIVATION_HASH=activationHash;globalThis.__testEnv.ADMIN_ACTIVATION_EXPIRES=String(Date.now()+3600000);
r=await activation.request('admin/activate','POST',{...activationBody,code:'AMOR-INVALIDO-TESTE'});ok(r.status===403&&!sql.prepare('SELECT id FROM admin_accounts').get(),'Wrong code cannot create an administrator');
globalThis.__testEnv.ADMIN_ACTIVATION_EXPIRES=String(Date.now()-1000);r=await activation.request('admin/activate','POST',activationBody);ok(r.status===403,'Expired first-access code is rejected');
globalThis.__testEnv.ADMIN_ACTIVATION_EXPIRES=String(Date.now()+3600000);
r=await activation.request('admin/activate','POST',{...activationBody,password:'curta'});ok(r.status===422,'First access enforces the normal password policy');
r=await activation.request('admin/activate','POST',activationBody);ok(r.status===201&&r.headers.get('set-cookie').includes('HttpOnly')&&r.headers.get('set-cookie').includes('Secure'),'Valid one-use code creates an administrator and a protected session without ChatGPT sign-in');
r=await activation.request('admin/data');ok(r.status===200,'The newly created login can operate the bakery panel');
const activated=sql.prepare('SELECT * FROM admin_accounts WHERE login=?').get('nova.admin');ok(activated.role==='admin'&&activated.password_hash.startsWith('scrypt:')&&sql.prepare("SELECT value FROM settings WHERE key='admin'").get().value===platformOwnerBefore,'Code activation hashes the password and preserves the original platform owner');
r=await activation.request('admin/activate','POST',{...activationBody,login:'outro.login'});ok(r.status===409&&sql.prepare('SELECT COUNT(*) n FROM admin_accounts').get().n===1,'A used code cannot create a second administrator');
await activation.request('admin/logout','POST',{});r=await activation.request('admin/login','POST',{login:activationBody.login,password});ok(r.status===200,'Subsequent access works with the selected login and password');
sql.prepare('DELETE FROM admin_sessions').run();sql.prepare('DELETE FROM admin_accounts').run();r=await activation.request('admin/activate','POST',activationBody);ok(r.status===409,'Deleting an account never re-enables its consumed activation code');
sql.prepare('DELETE FROM settings WHERE key=?').run('admin_activation_used:'+activationHash);
beforeBatch=queries=>{if(queries.some(q=>q.query.includes('commerce_guards')&&q.values[0]?.startsWith('activation:'))){beforeBatch=null;sql.prepare("INSERT INTO admin_accounts(id,name,login,password_hash,created_at,role) VALUES(?,?,?,?,?,'admin')").run(crypto.randomUUID(),'Existing admin','existing.admin',activated.password_hash,Date.now())}};
r=await activation.request('admin/activate','POST',activationBody);ok(r.status===409&&!sql.prepare('SELECT value FROM settings WHERE key=?').get('admin_activation_used:'+activationHash)&&sql.prepare('SELECT COUNT(*) n FROM admin_accounts').get().n===1,'Concurrent first access rolls back code consumption and preserves the existing administrator');

console.log(`Verified ${count} checks. No real payment or message sent.`);
}finally{sql.close();await rm(dir,{recursive:true,force:true})}
