'use client';
import {useState,useEffect} from 'react';
import {Textarea} from './ui/textarea';
import {toast} from 'sonner';
import {Input} from './ui/input';
import {Button} from './ui/button';
import {api,errorMessage} from '@/lib/client';
import {money,addressText} from '@/lib/commerce';
export default function AdminCustomers(){const [q,setQ]=useState(''),[filter,setFilter]=useState(''),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(true);useEffect(()=>{let active=true;setBusy(true);api('admin/customers?q='+encodeURIComponent(filter)).then(r=>{if(active){setRows(r.customers);setError('')}}).catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[filter]);return <><div className="section-toolbar"><div><h2>Clientes</h2><p>Contatos, endereços e compras, inclusive de convidados.</p></div></div><form className="history-filters" onSubmit={e=>{e.preventDefault();setFilter(q)}}><Input aria-label="Buscar cliente" placeholder="Nome ou telefone" value={q} onChange={e=>setQ(e.target.value)}/><Button>Buscar</Button></form>{error&&<p role="alert">{error}</p>}{busy?<p>Consultando clientes…</p>:!rows.length?<div className="admin-empty"><h3>Nenhum cliente encontrado</h3><p>Os clientes aparecem aqui depois do cadastro ou pedido.</p></div>:<div className="customer-grid">{rows.map(c=><article className="settings-card" key={c.user_id}><h3>{c.data.name}</h3><p>{c.data.phone}</p>{c.data.cpf&&<p>CPF: {c.data.cpf}</p>}{c.data.email&&<p>E-mail: {c.data.email}</p>}<p>{c.orders} pedidos · {money(c.spent)} em compras pagas</p>{c.data.address&&<p><strong>Endereço:</strong> {addressText(c.data.address)}</p>}<label className="field"><span>Observações internas</span><Textarea maxLength={2000} value={c.notes||''} onChange={e=>setRows(rs=>rs.map(row=>row.user_id===c.user_id?{...row,notes:e.target.value}:row))}/></label><Button variant="outline" onClick={async()=>{try{await api('admin/customers',{method:'PATCH',body:JSON.stringify({id:c.user_id,notes:c.notes||''})});toast.success('Observação salva.')}catch(e){toast.error(errorMessage(e))}}}>Salvar observação</Button><a className="text-link" href={'/painel/historico?cliente='+encodeURIComponent(c.data.name)}>Ver histórico de compras ↗</a></article>)}</div>}</>}
