'use client';
import {useState} from 'react';
import {Button} from './ui/button';
import {Input} from './ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from './ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from './ui/alert-dialog';
import {money} from '@/lib/commerce';
import {paymentAllowed} from '@/lib/payment-options';
import {api,errorMessage} from '@/lib/client';
import {toast} from 'sonner';
export function BudgetOffer({budget,config,onChanged}:{budget:any;config:any;onChanged:()=>void}){
 const [payment,setPayment]=useState(''),[email,setEmail]=useState(''),[cpf,setCpf]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),offer=budget.data.offer;
 if(budget.data.orderId)return <a className="btn-link" href="/pedidos">Acompanhar e pagar a encomenda</a>;
 if(!offer)return null;
 const online=!!config?.onlinePayment&&!['cash','card_machine'].includes(payment);
 async function answer(accept:boolean){setBusy(true);try{const r=await api('budgets/'+budget.id+'/answer',{method:'POST',body:JSON.stringify({accept,version:offer.version,payment:payment||undefined,email,cpf})});setConfirm(false);onChanged();if(r.order)location.href='/pedidos';else toast.success('Orçamento recusado.')}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
 return <div className="offer-summary"><strong>Proposta da confeitaria</strong><p>Total: <strong>{money(offer.total)}</strong> · Frete incluído: {money(offer.fee)}</p><p>Sinal combinado: <strong>{money(offer.deposit)}</strong> · Saldo: {money(offer.total-offer.deposit)}</p><p>Válido até {offer.expires.split('-').reverse().join('/')}</p><p className="preserve-lines">{offer.terms}</p>{budget.status==='Orçamento enviado'&&config&&<><label className="field"><span>Como deseja pagar?</span><Select value={payment} onValueChange={setPayment}><SelectTrigger><SelectValue placeholder="Escolha uma opção"/></SelectTrigger><SelectContent>{([['cash','Dinheiro'],['pix','Pix'],['card','Cartão online'],['card_machine','Maquininha']] as const).filter(([p])=>paymentAllowed(config.settings,budget.data.delivery,p,config.onlinePayment)).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></label><p>{online?'O pagamento online cobra o total antecipadamente.':'O preparo será liberado após a confeitaria confirmar o sinal combinado. O saldo será conferido antes de entregar ou retirar.'}</p>{online&&payment==='pix'&&['mercadopago','picpay'].includes(config.settings.paymentProvider)&&<><Input type="email" aria-label="E-mail para pagamento" placeholder="E-mail para pagamento" value={email} onChange={e=>setEmail(e.target.value)}/><Input aria-label="CPF para pagamento" placeholder="CPF" inputMode="numeric" maxLength={14} value={cpf} onChange={e=>setCpf(e.target.value)}/></>}<div className="budget-actions"><Button disabled={busy||!payment} onClick={()=>setConfirm(true)}>Aceitar e gerar pedido</Button><Button variant="outline" disabled={busy} onClick={()=>answer(false)}>Recusar proposta</Button></div><AlertDialog open={confirm} onOpenChange={setConfirm}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirmar encomenda?</AlertDialogTitle><AlertDialogDescription>Total de {money(offer.total)} para {budget.data.date.split('-').reverse().join('/')}. {online?'O pagamento online será do valor total.':'Sinal de '+money(offer.deposit)+' e saldo de '+money(offer.total-offer.deposit)+'.'} Ao aceitar, a proposta vira um pedido com essas condições.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Voltar</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void answer(true)}}>Confirmar proposta</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>}</div>;
}
