'use client';
import 'leaflet/dist/leaflet.css';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,Marker} from 'leaflet';
import {LocateFixed,MapPin,LoaderCircle,Check} from 'lucide-react';
import {Button} from './ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {api,errorMessage} from '@/lib/client';
import {addressSchema,type Address,type DeliveryLocation} from '@/lib/commerce';

export function ExactLocation({address,onChange,store=false}:{store?:boolean;address:Address;onChange:(point:DeliveryLocation)=>void}){
 const [open,setOpen]=useState(false),[draft,setDraft]=useState<DeliveryLocation|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const alive=useRef(true);useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[]);
 function show(){setDraft(address.location||null);setError('');setOpen(true)}
 function gps(){if(!navigator.geolocation){setError('Este navegador não oferece GPS. Marque o ponto no mapa.');return}setBusy(true);setError('');navigator.geolocation.getCurrentPosition(p=>{if(!alive.current)return;setDraft({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:Math.min(p.coords.accuracy,100000),source:'gps',confirmed:false});setBusy(false)},()=>{if(!alive.current)return;setBusy(false);setError('Localização não autorizada ou indisponível. Permita o acesso no navegador ou marque o ponto no mapa.')},{enableHighAccuracy:true,timeout:15000,maximumAge:0})}
 async function findAddress(){const parsed=addressSchema.safeParse(address);if(!parsed.success){setError('Preencha o endereço completo para encontrá-lo no mapa, ou use meu GPS.');return}setBusy(true);setError('');try{const p=await api('address/point',{method:'POST',body:JSON.stringify(parsed.data)});if(alive.current)setDraft({...p,source:'pin',confirmed:false})}catch(e){if(alive.current)setError(errorMessage(e))}finally{if(alive.current)setBusy(false)}}
 return <div className="exact-location"><strong><MapPin size={18}/>{store?'Localização da confeitaria':'Ponto exato da entrega'}</strong><p>{store?'Marque o ponto de saída das entregas.':'Além do endereço, confirme no mapa onde o motoboy deve chegar.'}</p><Button type="button" variant="outline" onClick={show}>{address.location?.confirmed?<Check size={17}/>:<MapPin size={17}/>} {address.location?.confirmed?'Localização confirmada · alterar':'Adicionar minha localização'}</Button>{address.location?.confirmed&&<small>{store?'As rotas de entrega partem deste ponto.':'O QR da via do motoboy abrirá este ponto. Não há acompanhamento em tempo real.'}</small>}<Dialog open={open} onOpenChange={setOpen}><DialogContent className="location-dialog"><DialogHeader><DialogTitle>{store?'Onde fica a confeitaria?':'Onde o motoboy deve chegar?'}</DialogTitle><DialogDescription>Use o GPS ou encontre o endereço. Arraste o marcador até a entrada correta e confirme.</DialogDescription></DialogHeader><div className="location-actions"><Button type="button" disabled={busy} onClick={gps}>{busy?<LoaderCircle className="spin"/>:<LocateFixed size={17}/>}Usar meu GPS</Button><Button type="button" variant="outline" disabled={busy} onClick={findAddress}>{store?'Buscar endereço preenchido':'Buscar meu endereço'}</Button></div>{error&&<p className="notice error" role="alert">{error}</p>}<LocationMap point={draft} onPick={p=>setDraft({...p,source:'pin',confirmed:false})}/>{draft?.source==='gps'&&draft.accuracy!=null&&<p className="small-muted">Precisão informada pelo GPS: cerca de {Math.round(draft.accuracy)} m.{draft.accuracy>100?' A precisão está baixa. Ajuste o marcador para a entrada correta.':' Confira se o marcador está no ponto de entrega.'}</p>}<Button type="button" disabled={!draft||busy} onClick={()=>{if(draft){onChange({...draft,confirmed:true});setOpen(false)}}}><Check size={18}/>Confirmar ponto de entrega</Button><p className="small-muted">A localização é salva somente neste endereço e pedido, para calcular a rota e orientar a entrega.</p></DialogContent></Dialog></div>;
}
function LocationMap({point,onPick}:{point:DeliveryLocation|null;onPick:(point:{lat:number;lng:number})=>void}){
 const element=useRef<HTMLDivElement>(null),map=useRef<LeafletMap|null>(null),marker=useRef<Marker|null>(null),pick=useRef(onPick),current=useRef(point);
 const [error,setError]=useState('');pick.current=onPick;current.current=point;
 useEffect(()=>{let gone=false,observer:ResizeObserver|undefined;void import('leaflet').then(L=>{if(gone||!element.current)return;const p=current.current;const m=L.map(element.current,{scrollWheelZoom:false}).setView(p?[p.lat,p.lng]:[-14.2,-51.9],p?18:4);map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>setError('O mapa não carregou. Você pode tentar novamente ou confirmar o ponto capturado pelo GPS.')).addTo(m);const pin=L.divIcon({className:'delivery-map-pin',html:'<span></span>',iconSize:[26,26],iconAnchor:[13,13]});const mk=L.marker(p?[p.lat,p.lng]:m.getCenter(),{icon:pin,draggable:true,keyboard:true,title:'Ponto de entrega · arraste para ajustar'});if(p)mk.addTo(m);marker.current=mk;mk.on('dragend',()=>{const pos=mk.getLatLng();pick.current({lat:pos.lat,lng:pos.lng})});m.on('click',e=>{mk.setLatLng(e.latlng).addTo(m);pick.current({lat:e.latlng.lat,lng:e.latlng.lng})});observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(element.current)}).catch(()=>setError('Não conseguimos carregar o mapa. Use o GPS para marcar sua localização.'));return()=>{gone=true;observer?.disconnect();map.current?.remove();map.current=null;marker.current=null}},[]);
 useEffect(()=>{if(point&&map.current&&marker.current){marker.current.setLatLng([point.lat,point.lng]).addTo(map.current);map.current.setView([point.lat,point.lng],Math.max(map.current.getZoom(),17))}},[point]);
 return <><div ref={element} className="delivery-map" aria-label="Mapa para escolher o ponto de entrega"/><Button type="button" variant="outline" onClick={()=>{const p=map.current?.getCenter();if(p)pick.current({lat:p.lat,lng:p.lng})}}>Usar o centro do mapa</Button>{error&&<p className="small-muted" role="status">{error}</p>}</>;
}
