'use client';
import {CardPayment} from './card-payment';
import {receivedAmount,remainingAmount} from '@/lib/payment-amounts';
import {money} from '@/lib/commerce';
import {useEffect,useState} from 'react';
import {Copy,Upload,RefreshCw} from 'lucide-react';
import {toast} from 'sonner';
import {Button} from './ui/button';
import {collectionInfo,paymentLabel,manualPayment} from '@/lib/order-display';
import {api,errorMessage} from '@/lib/client';
import {standardPhoto} from '@/lib/image-upload';
import type {Order} from '@/lib/commerce';
export function OrderPayment({order,admin=false}:{order:Order;admin?:boolean}){
 const [current,setCurrent]=useState(order),[qr,setQr]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>setCurrent(order),[order]);
 const pending=!['Pago','Estornado','Contestado','Estorno parcial'].includes(current.payment_status)&&!['Cancelado','Não retirado'].includes(current.status),manual=manualPayment(current),native=['mercadopago','picpay'].includes(current.data.paymentProvider||'')&&current.payment==='pix';
 async function check(quiet=false){if(!quiet)setBusy(true);try{const r=await api('orders/'+current.id+'/check',{method:'POST',body:'{}'});setCurrent(r.order);if(!quiet)toast.info(r.order.payment_status==='Pago'?'Pagamento confirmado!':'Aguardando confirmação do banco.')}catch(e){if(!quiet)toast.error(errorMessage(e))}finally{if(!quiet)setBusy(false)}}
 useEffect(()=>{if(admin||!pending||!native)return;const id=setInterval(()=>{if(document.visibilityState==='visible')void check(true)},15000);return()=>clearInterval(id)},[current.id,pending,native,admin]);
 useEffect(()=>{let active=true;if(current.data.pixCode)void import('qrcode').then(q=>q.toDataURL(current.data.pixCode!,{width:260,margin:2,errorCorrectionLevel:'M'})).then(url=>{if(active)setQr(url)});return()=>{active=false}},[current.data.pixCode]);
 async function proof(file?:File){if(!file)return;setBusy(true);try{const body=new FormData();body.append('file',await standardPhoto(file));await api('orders/'+current.id+'/proof',{method:'POST',body});setCurrent(o=>({...o,payment_status:'Comprovante em análise'}));toast.success('Comprovante enviado. A confeitaria vai conferir o recebimento.')}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
 const expired=!manual&&current.payment==='pix'&&(current.payment_status==='Expirado'||!!current.data.pixExpires&&current.data.pixExpires<Date.now());
 async function renew(){setBusy(true);try{const r=await api('orders/'+current.id+'/pay',{method:'POST',body:'{}'});if(r.order)setCurrent(r.order)}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
 const info=collectionInfo(current);return <div className="order-payment-block"><div className="notice"><strong>{info.title}</strong><p>{paymentLabel(current)} · {current.payment_status}</p><p>{info.detail}</p>{receivedAmount(current)>0&&<p>Recebido: {money(receivedAmount(current))} · Saldo: {money(remainingAmount(current))}</p>}{!!current.data.depositRequired&&<p>Sinal mínimo para o preparo: {money(current.data.depositRequired)}</p>}{current.data.dueDate&&<p>Encomenda para {current.data.dueDate.split('-').reverse().join('/')}</p>}</div>{!admin&&pending&&current.data.embeddedCard&&<CardPayment orderId={current.id} onPaid={()=>{setCurrent(o=>({...o,payment_status:'Pago',received:o.total}));toast.success('Pagamento confirmado pelo banco!')}}/>}{!admin&&current.data.pickupCode&&current.data.delivery==='pickup'&&<div className="pickup-code"><small>Seu código de retirada</small><strong>{current.data.pickupCode}</strong><p>Informe este código ao retirar o pedido na confeitaria.</p></div>}{pending&&expired&&!admin&&<div className="notice"><p>O prazo deste Pix terminou. Confira a situação e gere um novo código, se o banco confirmar o vencimento.</p><Button disabled={busy} onClick={renew}>Atualizar Pix vencido</Button></div>}{pending&&native&&!current.data.pixCode&&!admin&&<div className="notice"><p>Houve um erro no provedor de pagamento. Clique abaixo para gerar o código.</p><Button disabled={busy} onClick={renew}>Tentar novamente</Button></div>}{pending&&!expired&&current.data.pixCode&&<div className="pix-box"><h3>{manual?'Pix direto para a confeitaria':'Pague com Pix'}</h3>{qr&&<img className="payment-qr" src={qr} width={260} height={260} alt="QR Code para pagar este pedido com Pix"/>}{current.data.pixKey&&<p><strong>Chave Pix:</strong> {current.data.pixKey}<br/>Titular: {current.data.pixName}</p>}<p>{manual?'Confira o titular no aplicativo do banco e envie seu comprovante.':'Confira o valor e o recebedor no aplicativo do banco. O pedido atualiza após a confirmação.'}</p><textarea readOnly aria-label="Código Pix copia e cola" value={current.data.pixCode}/><Button onClick={()=>navigator.clipboard.writeText(current.data.pixCode!).then(()=>toast.success('Código Pix copiado.')).catch(()=>toast.error('Selecione o código para copiar.'))}><Copy size={16}/>Copiar Pix</Button>{native&&!admin&&<Button disabled={busy} variant="outline" onClick={()=>check()}><RefreshCw size={16}/>Verificar pagamento</Button>}{manual&&!admin&&<label className="reference-upload"><Upload size={16}/>{busy?'Enviando…':'Enviar comprovante'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>proof(e.target.files?.[0])}/></label>}</div>}</div>;
}
