'use client';
import {useState} from 'react';
import {Wallet,Check,LoaderCircle,Copy} from 'lucide-react';
import {WhatsAppWebJS} from './whatsapp-webjs';
import {Button} from './ui/button';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from './ui/select';
import type {StoreSettings} from '@/lib/commerce';
import {Field} from './store-settings';
import {api,errorMessage} from '@/lib/client';
import {toast} from 'sonner';
export function StoreConnections({settings,onChange,onSaveSettings,connections,onSaved}:{settings:StoreSettings;onChange:(s:StoreSettings)=>void;onSaveSettings:()=>Promise<void>;whatsapp:string;connections:any;onSaved:()=>Promise<void>}){
  const [inputs,setInputs]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[testingTag,setTestingTag]=useState(false);const origin=typeof window==='undefined'?'':window.location.origin;
  const field=(key:string,label:string,password=true)=><Field key={key} label={label} type={password?'password':'text'} value={inputs[key]||''} onChange={v=>setInputs(s=>({...s,[key]:v}))} placeholder={connections[key]?'Salvo · preencha para substituir':'Ainda não configurado'}/>;
  async function save(){setBusy(true);try{await api('admin/integrations',{method:'PUT',body:JSON.stringify(inputs)});setInputs({});await onSaveSettings();await onSaved();toast.success('Conexões salvas.')}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
  async function testTag(){setTestingTag(true);try{const res=await api('admin/integrations/infinitepay/test',{method:'POST',body:JSON.stringify({tag:connections.infiniteTag})});if(res.ok)toast.success('Validada: '+res.name);else toast.error(res.error||'Erro ao validar tag')}catch(e){toast.error(errorMessage(e))}finally{setTestingTag(false)}}
 const hook=(name:string)=><Button variant="outline" onClick={()=>navigator.clipboard.writeText(origin+'/api/webhooks/'+name).then(()=>toast.success('URL de notificação copiada.')).catch(()=>toast.error('Não foi possível copiar.'))}><Copy size={16}/>Copiar URL de notificações</Button>;
 return <><div className="section-toolbar"><div><h2>Conexões</h2><p>WhatsApp, pagamentos e cálculo de entrega em um só lugar.</p></div><Button onClick={save} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Check size={17}/>}Salvar conexões</Button></div><WhatsAppWebJS onSaved={onSaved}/><div className="settings-grid">
 <section className="settings-card"><h3><Wallet size={20}/>Pagamento on-line</h3><div className="form-stack"><label className="field"><span>Provedor principal</span><Select value={settings.paymentProvider} onValueChange={(v:any)=>onChange({...settings,paymentProvider:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="infinitepay">InfinitePay</SelectItem><SelectItem value="picpay">PicPay</SelectItem><SelectItem value="mercadopago">Mercado Pago</SelectItem><SelectItem value="pagbank">PagBank</SelectItem></SelectContent></Select></label><details><summary style={{cursor:'pointer',fontWeight:600,paddingTop:'8px',paddingBottom:'8px'}}>Pix com conferência manual</summary><div className="form-stack"><Field label="Chave Pix" value={settings.pixKey} onChange={v=>onChange({...settings,pixKey:v.trim()})}/><Field label="Nome do titular" value={settings.pixName} onChange={v=>onChange({...settings,pixName:v})}/><Field label="Cidade" value={settings.pixCity} onChange={v=>onChange({...settings,pixCity:v})}/></div><p className="small-muted">Usado caso nenhum provedor acima esteja conectado.</p></details></div></section>
  <section className="settings-card"><h3><Wallet size={20}/>InfinitePay <small>· padrão</small></h3><span className="connection-pill">{connections.infiniteTag?'Tag salva':'Não configurado'}</span><p>Pix e cartão no checkout da InfinitePay. A confirmação volta automaticamente ao pedido.</p><details><summary style={{cursor:'pointer',fontWeight:600,paddingTop:'8px',paddingBottom:'8px'}}>Configuração técnica</summary><div className="form-stack">{connections.infiniteTag&&!inputs.infiniteTag_edit?<div style={{display:'flex',alignItems:'center',gap:'1rem',padding:'8px 12px',background:'var(--surface-sunken)',borderRadius:'8px',fontSize:'0.95rem'}}><span style={{flex:1}}>Tag da loja: <strong>${connections.infiniteTag}</strong></span><Button variant="outline" size="sm" onClick={testTag} disabled={testingTag}>{testingTag?<LoaderCircle className="spin size-3"/>:'Testar tag'}</Button><Button variant="outline" size="sm" onClick={()=>setInputs(s=>({...s,infiniteTag_edit:'1'}))}>Alterar</Button></div>:<div style={{display:'flex',gap:'8px',alignItems:'flex-end'}}><div style={{flex:1}}>{field('infiniteTag','InfiniteTag da confeitaria',false)}</div><Button onClick={save} disabled={busy||!inputs.infiniteTag}>Ativar</Button></div>}<p className="small-muted">Informe a tag da conta, sem o cifrão. Exemplo: confeitando.</p>{hook('infinitepay')}</div><a href="https://www.infinitepay.io/checkout-documentacao" target="_blank" rel="noreferrer">Ajuda da InfinitePay ↗</a></details></section>
 <section className="settings-card"><h3><Wallet size={20}/>Mercado Pago</h3><span className="connection-pill">{connections.mpToken&&connections.mpWebhookSecret?'Credenciais salvas':'Não configurado'}</span><p>Pix e cartão dentro do site. Configure a Public Key para habilitar o formulário de cartão.</p><details><summary style={{cursor:'pointer',fontWeight:600,paddingTop:'8px',paddingBottom:'8px'}}>Configuração técnica</summary><div className="form-stack">{field('mpToken','Access Token de produção')}{field('mpPublicKey','Public Key de produção',false)}{field('mpWebhookSecret','Assinatura secreta das notificações')}{hook('mercadopago')}</div><div className="setup-guide"><p>Em Suas integrações no Mercado Pago, copie o Access Token. Configure a URL de notificações acima para o evento Pagamentos e salve a assinatura secreta aqui.</p><a href="https://www.mercadopago.com.br/developers/panel/app" target="_blank" rel="noreferrer">Abrir integrações ↗</a></div></details></section>
 <section className="settings-card"><h3><Wallet size={20}/>PagBank / PagSeguro</h3><span className="connection-pill">{connections.pbToken?'Token salvo':'Não configurado'}</span><p>Pix e cartão no checkout do PagBank, com atualização automática.</p><details><summary style={{cursor:'pointer',fontWeight:600,paddingTop:'8px',paddingBottom:'8px'}}>Configuração técnica</summary><div className="form-stack">{field('pbToken','Token de produção')}{hook('pagbank')}</div><p className="small-muted">A conta precisa estar habilitada para a API de Checkout.</p><a href="https://developer.pagbank.com.br/" target="_blank" rel="noreferrer">Ajuda do PagBank ↗</a></details></section>
 <section className="settings-card"><h3><Wallet size={20}/>PicPay</h3><span className="connection-pill">{connections.ppClientId&&connections.ppClientSecret?'Credenciais salvas':'Não configurado'}</span><p>Pix dentro do site. A confirmação é consultada diretamente na conta PicPay.</p><details><summary style={{cursor:'pointer',fontWeight:600,paddingTop:'8px',paddingBottom:'8px'}}>Configuração técnica</summary><div className="form-stack">{field('ppClientId','Client ID')}{field('ppClientSecret','Client Secret')}{field('ppWebhookToken','Token das notificações')}{hook('picpay')}<p className="small-muted">Em Ajustes → Meu checkout, cadastre a URL de notificações. Salve aqui o token exibido pelo PicPay.</p></div><a href="https://painel-empresas.picpay.com/" target="_blank" rel="noreferrer">Abrir painel PicPay Empresas ↗</a></details></section></div></>;
}
