'use client';
import {useEffect,useState} from 'react';
import {MessageCircle,LoaderCircle,RefreshCw,Unplug,Copy} from 'lucide-react';
import {Button} from './ui/button';
import {api,errorMessage} from '@/lib/client';
import {toast} from 'sonner';

export function WhatsAppWebJS({onSaved}:{onSaved:()=>Promise<void>}){
 const [status,setStatus]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[pairing,setPairing]=useState<{code:string;expires:number}|null>(null);
 async function refresh(){try{setStatus(await api('admin/whatsapp/bridge'));setError('')}catch(e){setError(errorMessage(e))}}
 useEffect(()=>{void refresh();const interval=setInterval(()=>{if(document.visibilityState==='visible')void refresh()},4000);return()=>clearInterval(interval)},[]);
 async function command(action:string){setBusy(true);try{setStatus(await api('admin/whatsapp/'+action,{method:'POST',body:'{}'}));await onSaved();toast.success(action==='connect'?'Conexão solicitada. Aguarde o QR code.':'Desconexão solicitada.')}catch(e){toast.error(errorMessage(e))}finally{setBusy(false);void refresh()}}
 async function generateCode(){setBusy(true);try{setPairing(await api('admin/whatsapp/pairing',{method:'POST',body:'{}'}))}catch(e){toast.error(errorMessage(e))}finally{setBusy(false)}}
 const labels:Record<string,string>={not_installed:'Instale o conector para começar',offline:'Conector offline',disconnected:'WhatsApp desconectado',starting:'Abrindo o WhatsApp…',qr:'Leia o QR code com o celular',authenticated:'Finalizando a conexão…',ready:'WhatsApp conectado',auth_failure:'A autenticação falhou · reconecte',error:'O conector encontrou um erro'};
 return <section className="settings-card whatsapp-simple"><h3><MessageCircle size={20}/>WhatsApp por QR code</h3><p>Conecte o número da confeitaria para enviar os avisos de pedido recebido, pagamento confirmado, preparo, entrega e retirada.</p><span className="connection-pill" role="status">{status?status.desired==='disconnected'&&status.online?'WhatsApp desconectado':labels[status.state]||'Consultando…':'Consultando conexão…'}</span>{error&&<p className="notice error" role="alert">{error}</p>}{status?.phone&&<p>Número conectado: +{status.phone}</p>}<div className="wa-controls"><Button disabled={busy||status?.connected} onClick={()=>command('connect')}>{busy?<LoaderCircle className="spin"/>:<MessageCircle size={17}/>}Conectar WhatsApp</Button>{status?.installed&&<Button variant="outline" disabled={busy} onClick={()=>command('disconnect')}><Unplug size={17}/>Desconectar</Button>}<Button variant="ghost" aria-label="Atualizar conexão do WhatsApp" onClick={refresh}><RefreshCw size={17}/></Button></div>{status?.desired==='connected'&&status?.qr&&<><img className="wa-qr" src={status.qr} alt="QR code de conexão do WhatsApp da confeitaria"/><p>No celular: <strong>WhatsApp → Aparelhos conectados → Conectar aparelho</strong>. Aponte a câmera para este QR.</p></>}{status?.online&&status.desired==='connected'&&!status.qr&&!status.connected&&<p>Aguarde o conector abrir o WhatsApp. Se a sessão já estiver salva, ele poderá reconectar sem pedir outro QR.</p>}{!status?.installed&&<p className="notice">O sistema de envio está sendo configurado pelo suporte. Assim que estiver pronto, clique em Conectar WhatsApp.</p>}<p className="small-muted">A conexão pode cair se o celular ficar muito tempo sem internet. Volte nesta tela para reconectar se necessário.</p></section>;
}
