import {z} from 'zod';
import {db,settings,unpackOrder,HttpError} from './server';
import {statuses,type Order} from './commerce';
export const dateOnly=z.string().regex(/^20\d{2}-\d{2}-\d{2}$/,'Informe uma data válida.').refine(v=>{const n=new Date(v+'T12:00:00Z');return Number.isFinite(n.getTime())&&n.toISOString().slice(0,10)===v},'Informe uma data válida.');
export function localDay(time:number,zone:string){return new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(time))}
export function dateBoundary(day:string,zone:string){dateOnly.parse(day);let time=Date.parse(day+'T00:00:00Z');for(let i=0;i<3;i++){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(time));const p=Object.fromEntries(parts.map(p=>[p.type,p.value]));const represented=Date.parse(`${p.year}-${p.month}-${p.day}T${p.hour}:${p.minute}:${p.second}Z`);time+=Date.parse(day+'T00:00:00Z')-represented;}return time}
export async function orderStats(){const s=await settings(),start=dateBoundary(localDay(Date.now(),s.timezone),s.timezone);const [row,receipts]=await Promise.all([db().prepare("SELECT SUM(CASE WHEN created_at>=? THEN 1 ELSE 0 END) today,SUM(CASE WHEN status NOT IN ('Concluído','Cancelado','Entregue','Retirado','Não retirado') THEN 1 ELSE 0 END) active FROM orders").bind(start).first<any>(),db().prepare('SELECT COALESCE(SUM(amount),0) paid FROM payment_receipts WHERE occurred_at>=?').bind(start).first<any>()]);return {today:row.today||0,active:row.active||0,paid:receipts.paid}}
export async function withNotifications(rows:any[]){if(!rows.length)return [];const r=await db().prepare('SELECT * FROM notifications WHERE order_id IN ('+rows.map(()=>'?').join(',')+')').bind(...rows.map(o=>o.id)).all<any>();const grouped=new Map<string,any[]>();for(const n of r.results)grouped.set(n.order_id,[...(grouped.get(n.order_id)||[]),n]);return rows.map(o=>({...unpackOrder(o),notifications:grouped.get(o.id)||[]}))}
export async function orderHistory(req:Request){
 const p=new URL(req.url).searchParams,s=await settings(),from=p.get('from')||'',to=p.get('to')||'',status=p.get('status')||'Todos',dateBasis=z.enum(['order','receipt']).parse(p.get('dateBasis')||'order'),page=z.coerce.number().int().min(1).max(100000).parse(p.get('page')||1);
 if(from)dateOnly.parse(from);if(to)dateOnly.parse(to);if(from&&to&&from>to)throw new HttpError(422,'A data inicial deve ser anterior ou igual à final.');if(status!=='Todos'&&!statuses.includes(status))throw new HttpError(422,'Etapa inválida.');
 const start=from?dateBoundary(from,s.timezone):0,end=to?dateBoundary(new Date(Date.parse(to+'T12:00:00Z')+86400000).toISOString().slice(0,10),s.timezone):Date.now()+1;
 const clauses:string[]=[],values:(string|number)[]=[];
 if(dateBasis==='order'){clauses.push('o.created_at>=? AND o.created_at<?');values.push(start,end)}else{clauses.push('EXISTS(SELECT 1 FROM payment_receipts r WHERE r.order_id=o.id AND r.occurred_at>=? AND r.occurred_at<?)');values.push(start,end)}
 if(status!=='Todos'){clauses.push('o.status=?');values.push(status)}
 for(const [key,expression] of [['payment','o.payment'],['paymentStatus','o.payment_status'],['delivery',"json_extract(o.data,'$.delivery')"],['provider',"json_extract(o.data,'$.paymentProvider')"]]){const value=p.get(key);if(value&&value!=='Todos'){if(key==='paymentStatus'&&value==='Pendentes'){clauses.push("o.payment_status NOT IN ('Pago','Estornado','Contestado','Expirado','Recusado') AND o.status NOT IN ('Cancelado','Não retirado') AND o.total > o.received")}else{clauses.push(expression+'=?');values.push(value.slice(0,80))}}}
 const search=p.get('search');if(search){clauses.push("(o.code LIKE ? OR json_extract(o.data,'$.profile.name') LIKE ? OR json_extract(o.data,'$.profile.phone') LIKE ?)");values.push(...Array(3).fill('%'+search.slice(0,100)+'%'))}
 const select='SELECT o.* FROM orders o WHERE '+clauses.join(' AND '),cte='WITH selected AS ('+select+') ',receiptTime=dateBasis==='receipt'?' AND r.occurred_at>='+start+' AND r.occurred_at<'+end:'';
 const [metrics,financial,byPayment,bestSellers,customers]=await Promise.all([
  db().prepare(cte+"SELECT COUNT(*) count,COALESCE(SUM(CASE WHEN status NOT IN ('Cancelado','Não retirado') THEN total ELSE 0 END),0) sales,COALESCE(SUM(CASE WHEN status NOT IN ('Cancelado','Não retirado') AND payment_status NOT IN ('Estornado','Contestado','Estorno parcial') THEN MAX(0,total-received) ELSE 0 END),0) pending,COALESCE(SUM(CASE WHEN status NOT IN ('Cancelado','Não retirado') THEN json_extract(data,'$.fee') ELSE 0 END),0) freight,COALESCE(SUM(CASE WHEN status='Cancelado' THEN 1 ELSE 0 END),0) canceled FROM selected").bind(...values).first<any>(),
  db().prepare(cte+"SELECT COALESCE(SUM(CASE WHEN r.amount>0 THEN r.amount ELSE 0 END),0) paid,COALESCE(SUM(CASE WHEN r.amount<0 AND r.kind='refund' THEN -r.amount ELSE 0 END),0) refunded,COALESCE(SUM(CASE WHEN r.kind='chargeback' THEN -r.amount ELSE 0 END),0) chargebacks,COALESCE(SUM(r.amount),0) net,COUNT(DISTINCT CASE WHEN r.amount>0 THEN r.order_id END) paidOrders FROM payment_receipts r JOIN selected o ON o.id=r.order_id WHERE 1=1"+receiptTime).bind(...values).first<any>(),
  db().prepare(cte+"SELECT r.method payment,COUNT(DISTINCT r.order_id) count,SUM(r.amount) total FROM payment_receipts r JOIN selected o ON o.id=r.order_id WHERE r.amount>0"+receiptTime+' GROUP BY r.method').bind(...values).all<any>(),
  db().prepare(cte+"SELECT json_extract(j.value,'$.name') name,SUM(json_extract(j.value,'$.quantity')) quantity FROM selected o,json_each(o.data,'$.items') j WHERE o.received=o.total AND o.payment_status='Pago' GROUP BY name ORDER BY quantity DESC LIMIT 5").bind(...values).all<any>(),
  db().prepare(cte+"SELECT COUNT(*) customers,COALESCE(SUM(CASE WHEN (SELECT COUNT(*) FROM orders all_o WHERE all_o.user_id=x.user_id AND all_o.status NOT IN ('Cancelado','Não retirado') AND all_o.created_at<?)>1 THEN 1 ELSE 0 END),0) recurringCustomers FROM (SELECT DISTINCT user_id FROM selected WHERE status NOT IN ('Cancelado','Não retirado')) x").bind(...values,end).first<any>()
 ]);
 const combined={...metrics,...financial,...customers,newCustomers:customers.customers-customers.recurringCustomers};
 if(p.get('export')==='1'){
  const rows=await db().prepare(cte+'SELECT * FROM selected ORDER BY created_at DESC LIMIT 10000').bind(...values).all<any>();
  const cell=(v:unknown)=>{let text=String(v??'');if(/^[=+@-]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"'},brl=(v:number)=>(v/100).toFixed(2).replace('.',',');
  const data=[['Pedido','Data do pedido','Último recebimento','Cliente','Tipo','Etapa','Forma','Situação','Total (R$)','Recebido líquido acumulado (R$)','Saldo (R$)','Frete (R$)'],...rows.results.map(raw=>{const o:Order=unpackOrder(raw);return [o.code,new Date(o.created_at).toLocaleString('pt-BR',{timeZone:s.timezone}),o.paid_at?new Date(o.paid_at).toLocaleString('pt-BR',{timeZone:s.timezone}):'',o.data.profile.name,o.data.delivery==='pickup'?'Retirada':'Entrega',o.status,o.payment,o.payment_status,brl(o.total),brl(o.received||0),brl(Math.max(0,o.total-(o.received||0))),brl(o.data.fee)]})];
  return new Response('\ufeff'+data.map(row=>row.map(cell).join(';')).join('\r\n'),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':'attachment; filename="pedidos.csv"','Cache-Control':'no-store'}});
 }
 const rows=await db().prepare(cte+'SELECT * FROM selected ORDER BY created_at DESC,id DESC LIMIT 40 OFFSET ?').bind(...values,(page-1)*40).all<any>();
 return {metrics:combined,byPayment:byPayment.results,bestSellers:bestSellers.results,orders:await withNotifications(rows.results),total:metrics.count,page,pages:Math.ceil(metrics.count/40),timezone:s.timezone,dateBasis};
}

export function productionOrders(rows:any[]){return rows.map(row=>{const o:Order=unpackOrder(row);return {...o,total:0,received:0,paid_at:null,user_id:'',payment_id:null,checkout_url:null,data:{items:o.data.items.map(i=>({...i,price:0})),delivery:o.data.delivery,fee:0,note:o.data.note,change:null,paymentProvider:o.data.paymentProvider,profile:{name:'Pedido #'+o.code,cpf:'',email:'',phone:'',whatsappConsent:false}}}})}
