import { z } from 'zod';
import { defaultHours,type Hours } from './store-hours';
export const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
export const categories=['Todos os doces','Bolos','Docinhos','Brownies','Cookies'];
export type Product={stock?:number|null;sort_order?:number;sold_out?:number;id:string;name:string;description:string;price:number;category:string;image:string;active:number;demo:number;tag:string;created_at:number;likes?:number;liked?:boolean;comments?:number};
export const initialProducts:Product[]=[
{id:'demo-1',name:'Bolo de morango',description:'Massa leve, creme delicado e morangos frescos. Um clássico para celebrar.',price:12900,category:'Bolos',image:'/images/strawberry-cake.jpg',active:1,demo:1,tag:'Para compartilhar',created_at:1},
{id:'demo-2',name:'Caixinha de brigadeiros',description:'Chocolate, carinho e aquele sabor de infância. Caixa com 6 unidades.',price:2400,category:'Docinhos',image:'/images/brigadeiros.jpg',active:1,demo:1,tag:'Um pequeno carinho',created_at:2},
{id:'demo-3',name:'Brownie de chocolate',description:'Casquinha delicada por fora, chocolate intenso e macio por dentro.',price:1400,category:'Brownies',image:'/images/brownies.jpg',active:1,demo:1,tag:'Chocolate de verdade',created_at:3},
{id:'demo-4',name:'Cookie artesanal',description:'Douradinho, macio no centro e com generosos pedaços de chocolate.',price:1200,category:'Cookies',image:'/images/cookies.jpg',active:1,demo:1,tag:'Feito à mão',created_at:4},
{id:'demo-5',name:'Brigadeiro tradicional',description:'Brigadeiro de chocolate finalizado com granulado. Unidade de 25 g.',price:450,category:'Docinhos',image:'/images/brigadeiros-tray.jpg',active:1,demo:1,tag:'Clássico da casa',created_at:5}
];
export const defaultSettings={name:'Confeitando com Amor',logo:'/brand-transparent.png',favicon:'/avatar.jpg',searchVerification:'',budgetWhenClosed:true,cakeFlavors:[] as string[],sweetFlavors:[] as string[],paymentRules:{delivery:{cash:true,card_machine:true,pix:true,card:true},pickup:{cash:true,card_machine:true,pix:true,card:true}},open:false,hoursMode:'closed' as 'auto'|'open'|'closed',hours:defaultHours as Hours,timezone:'America/Sao_Paulo',paymentProvider:'infinitepay' as 'infinitepay'|'mercadopago'|'pagbank'|'picpay',storeAddress:'',lat:null as number|null,lng:null as number|null,exceptions:[] as {date:string;closed:boolean}[],overrideUntil:0,minFee:0,pickupPrepaid:false,baseFee:500,perKm:150,maxKm:15,pickup:true,cash:true,cardOnDelivery:true,prepMin:40,prepMax:60,whatsapp:'',pixKey:'',pixName:'',pixCity:'',whatsappEnabled:false,whatsappMode:'webjs' as 'webjs'|'cloud'};
export type StoreSettings=typeof defaultSettings;
export const cpfValid=(value:string)=>{const s=value.replace(/\D/g,'');if(!/^\d{11}$/.test(s)||/^(\d)\1+$/.test(s))return false;for(let n=9;n<11;n++){let sum=0;for(let i=0;i<n;i++)sum+=Number(s[i])*(n+1-i);let d=(sum*10)%11;if(d===10)d=0;if(d!==Number(s[n]))return false}return true};
export const locationSchema=z.object({lat:z.number().finite().min(-90).max(90),lng:z.number().finite().min(-180).max(180),accuracy:z.number().finite().min(0).max(100000).optional(),source:z.enum(['gps','pin']),confirmed:z.boolean()});
export type DeliveryLocation=z.infer<typeof locationSchema>;
export const addressSchema=z.object({cep:z.string().regex(/^\d{5}-?\d{3}$/,'Informe um CEP válido'),street:z.string().trim().min(3,'Informe a rua').max(150),number:z.string().trim().min(1,'Informe o número').max(20),district:z.string().trim().min(2,'Informe o bairro').max(100),city:z.string().trim().min(2,'Informe a cidade').max(100),state:z.string().regex(/^[A-Z]{2}$/,'Informe a UF'),complement:z.string().max(150).default(''),location:locationSchema.optional()});
export type Address=z.infer<typeof addressSchema>;
export const emptyAddress:Address={cep:'',street:'',number:'',district:'',city:'',state:'',complement:''};
export const addressText=(a:Address)=>`${a.street}, ${a.number}, ${a.district}, ${a.city} - ${a.state}, ${a.cep}${a.complement?' · '+a.complement:''}`;
export const profileSchema=z.object({name:z.string().trim().min(3,'Informe seu nome completo').max(120),cpf:z.string().default('').refine(v=>!v||cpfValid(v),'CPF inválido'),email:z.union([z.string().email('E-mail inválido'),z.literal('')]).default(''),phone:z.string().transform(s=>s.replace(/\D/g,'')).refine(s=>/^\d{10,11}$/.test(s),'Telefone inválido, inclua o DDD'),address:addressSchema.optional(),whatsappConsent:z.boolean().default(false)});
export type Profile=z.infer<typeof profileSchema>;
export type Order={received?:number;paid_at?:number|null;payment_id?:string|null;id:string;code:string;user_id:string;total:number;status:string;payment:string;payment_status:string;checkout_url?:string;created_at:number;data:{storeName?:string;depositRequired?:number;budgetId?:string;dueDate?:string;terms?:string;embeddedCard?:boolean;items:{id:string;name:string;price:number;quantity:number;image:string;note?:string;stockTracked?:boolean}[];profile:Profile;address?:Address;delivery:string;fee:number;distance?:number;paymentProvider?:'infinitepay'|'mercadopago'|'pagbank'|'picpay'|'manual';trackingToken?:string;pickupCode?:string;invoiceSlug?:string;transactionNsu?:string;pixExpires?:number;pixGeneration?:string;ppChargeId?:string;note:string;change:number|null;pixCode?:string;pixKey?:string;pixName?:string};notifications?:{recipient:string;status:string;detail:string}[]};
export const statuses=['Recebido','Em preparo','Pronto para entrega','Saiu para entrega','Pronto para retirada','Entregue','Retirado','Concluído','Não retirado','Cancelado'];
export function pixPayload(key:string,name:string,city:string,amount:number,reference:string){
 const tlv=(i:string,s:string)=>i+s.length.toString().padStart(2,'0')+s;
 const clean=(s:string,n:number)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9 ]/g,'').slice(0,n);
 const payload=tlv('00','01')+tlv('26',tlv('00','br.gov.bcb.pix')+tlv('01',key))+tlv('52','0000')+tlv('53','986')+tlv('54',(amount/100).toFixed(2))+tlv('58','BR')+tlv('59',clean(name,25))+tlv('60',clean(city,15))+tlv('62',tlv('05',reference.replace(/[^a-zA-Z0-9]/g,'').slice(0,25)))+'6304';
 let crc=0xffff;for(let i=0;i<payload.length;i++){crc^=payload.charCodeAt(i)<<8;for(let j=0;j<8;j++)crc=(crc&0x8000)?((crc<<1)^0x1021):(crc<<1);crc&=0xffff}return payload+crc.toString(16).toUpperCase().padStart(4,'0');
}
