import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { defaultSettings, initialProducts, categories, pixPayload, type StoreSettings } from './commerce';
export const runtime=env as unknown as {DB?:D1Database;BUCKET?:R2Bucket;APP_SECRET?:string;ADMIN_SETUP_CODE?:string;ADMIN_ACTIVATION_HASH?:string;ADMIN_ACTIVATION_EXPIRES?:string;PUBLIC_URL?:string};
export function db(){if(!runtime.DB)throw new Error('Serviço indisponível. Tente novamente em instantes.');return runtime.DB}
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export async function identity(){const user=await getChatGPTUser();if(!user)throw new HttpError(401,'Entre para salvar seu cadastro e continuar.');return user}
export async function admin(req:Request){const {panelUser}=await import('./admin-auth');const u=await panelUser(req);if(!u)throw new HttpError(401,'Entre no painel para continuar.');return u}
export async function getSetting(key:string){return (await db().prepare('SELECT value FROM settings WHERE key=?').bind(key).first<{value:string}>())?.value??null}
export async function putSetting(key:string,value:string){await db().prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,value).run()}
export async function settings():Promise<StoreSettings>{const v=await getSetting('store');const stored=v?JSON.parse(v):{};delete stored.locationLink;return {...defaultSettings,...stored,hoursMode:stored.hoursMode??(stored.open?'open':'closed')}}
export async function products(all=false){const r=await db().prepare(`SELECT * FROM products ${all?'':'WHERE active=1'} ORDER BY sort_order ASC,created_at DESC`).all();if(r.results.length)return r.results;const initialized=await getSetting('catalog_initialized');return initialized?[]:initialProducts}
export async function initializeCatalog(){if(await getSetting('catalog_initialized'))return;await db().batch([...initialProducts.map(p=>db().prepare('INSERT OR IGNORE INTO products (id,name,description,price,category,image,active,demo,tag,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(p.id,p.name,p.description,p.price,p.category,p.image,p.active,p.demo,p.tag,p.created_at)),db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('catalog_initialized','1')")])}
async function encryptionKey(){if(!runtime.APP_SECRET)throw new HttpError(503,'Conexões indisponíveis. Contate o responsável pelo site.');return crypto.subtle.importKey('raw',new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(runtime.APP_SECRET))),{name:'AES-GCM'},false,['encrypt','decrypt'])}
export async function secrets():Promise<Record<string,string>>{const s=await getSetting('integrations');if(!s)return {};const [iv,cipher]=s.split('.').map(s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0)));const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv},await encryptionKey(),cipher);return JSON.parse(new TextDecoder().decode(plain))}
export async function saveSecrets(s:Record<string,string>){const iv=crypto.getRandomValues(new Uint8Array(12));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(),new TextEncoder().encode(JSON.stringify(s))));const encode=(a:Uint8Array)=>btoa(Array.from(a,c=>String.fromCharCode(c)).join(''));await putSetting('integrations',encode(iv)+'.'+encode(cipher))}
export async function fetchJSON(url:string,options:RequestInit={}){const r=await fetch(url,{...options,signal:AbortSignal.timeout(12000)});if(!r.ok)throw new HttpError(502,'O serviço de conexão não respondeu. Tente novamente.');return r.json() as Promise<any>}
export function sameOrigin(req:Request){const o=req.headers.get('origin');if(!o||(process.env.NODE_ENV!=='development'&&o!==new URL(req.url).origin))throw new HttpError(403,'Solicitação não autorizada.')}
export function unpackOrder(o:any){const data=JSON.parse(o.data);if(data.paymentProvider==='manual'&&data.pixKey&&data.pixCity){const received=o.received??0,amount=data.depositRequired&&received<data.depositRequired?data.depositRequired-received:Math.max(0,o.total-received);if(amount>0)data.pixCode=pixPayload(data.pixKey,data.pixName,data.pixCity,amount,o.code);else delete data.pixCode}return {...o,data}}

export async function categoryList():Promise<string[]>{const saved=await getSetting('categories');return saved?JSON.parse(saved):categories.slice(1)}
export async function catalogSocial(items:any[],userId?:string){if(!items.length)return items;const result=await db().prepare('SELECT p.id,(SELECT COUNT(*) FROM product_likes l WHERE l.product_id=p.id) AS likes,(SELECT COUNT(*) FROM product_comments c WHERE c.product_id=p.id) AS comments,EXISTS(SELECT 1 FROM product_likes l WHERE l.product_id=p.id AND l.user_id=?) AS liked FROM products p').bind(userId??'').all<any>();const social=new Map(result.results.map(r=>[r.id,r]));return items.map(p=>({...p,likes:0,comments:0,...social.get(p.id),liked:!!social.get(p.id)?.liked}))}
