import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,index,primaryKey,check} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const adminAccounts=sqliteTable('admin_accounts',{id:text('id').primaryKey(),name:text('name').notNull(),login:text('login').notNull().unique(),role:text('role').notNull().default('admin'),active:integer('active').notNull().default(1),passwordHash:text('password_hash').notNull(),createdAt:integer('created_at').notNull()});
export const adminSessions=sqliteTable('admin_sessions',{tokenHash:text('token_hash').primaryKey(),accountId:text('account_id').notNull().references(()=>adminAccounts.id,{onDelete:'cascade'}),expires:integer('expires').notNull()},t=>[index('admin_sessions_account').on(t.accountId)]);
export const budgets=sqliteTable('budgets',{id:text('id').primaryKey(),userId:text('user_id').notNull(),requestId:text('request_id').notNull().unique(),code:text('code').notNull(),data:text('data').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[index('budgets_user_created').on(t.userId,t.createdAt),index('budgets_created').on(t.createdAt)]);
export const budgetAttachments=sqliteTable('budget_attachments',{originalKey:text('original_key'),originalType:text('original_type'),id:text('id').primaryKey(),userId:text('user_id').notNull(),budgetId:text('budget_id').references(()=>budgets.id),objectKey:text('object_key').notNull(),contentType:text('content_type').notNull(),createdAt:integer('created_at').notNull()},t=>[index('budget_attachments_user').on(t.userId,t.budgetId)]);
export const products=sqliteTable('products',{stock:integer('stock'),sortOrder:integer('sort_order').notNull().default(0),soldOut:integer('sold_out').notNull().default(0),id:text('id').primaryKey(),name:text('name').notNull(),description:text('description').notNull(),price:integer('price').notNull(),category:text('category').notNull(),image:text('image').notNull(),active:integer('active').notNull().default(1),demo:integer('demo').notNull().default(0),tag:text('tag').notNull().default(''),createdAt:integer('created_at').notNull()});
export const profiles=sqliteTable('profiles',{notes:text('notes').notNull().default(''),userId:text('user_id').primaryKey(),data:text('data').notNull(),updatedAt:integer('updated_at').notNull()});
export const quotes=sqliteTable('quotes',{id:text('id').primaryKey(),userId:text('user_id').notNull(),address:text('address').notNull(),distance:integer('distance').notNull(),fee:integer('fee').notNull(),expires:integer('expires').notNull()});
export const orders=sqliteTable('orders',{received:integer('received').notNull().default(0),paidAt:integer('paid_at'),id:text('id').primaryKey(),userId:text('user_id').notNull(),requestId:text('request_id').notNull().unique(),code:text('code').notNull(),data:text('data').notNull(),total:integer('total').notNull(),status:text('status').notNull(),payment:text('payment').notNull(),paymentStatus:text('payment_status').notNull(),paymentId:text('payment_id'),checkoutUrl:text('checkout_url'),createdAt:integer('created_at').notNull()},t=>[index('orders_user_created').on(t.userId,t.createdAt),index('orders_created').on(t.createdAt)]);
export const notifications=sqliteTable('notifications',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),recipient:text('recipient').notNull(),status:text('status').notNull(),detail:text('detail').notNull().default('')},t=>[index('notifications_order').on(t.orderId)]);

export const productLikes=sqliteTable('product_likes',{productId:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),userId:text('user_id').notNull(),createdAt:integer('created_at').notNull()},t=>[primaryKey({columns:[t.productId,t.userId]})]);
export const productComments=sqliteTable('product_comments',{id:text('id').primaryKey(),productId:text('product_id').notNull().references(()=>products.id,{onDelete:'cascade'}),userId:text('user_id').notNull(),name:text('name').notNull(),body:text('body').notNull(),createdAt:integer('created_at').notNull()},t=>[index('comments_product_created').on(t.productId,t.createdAt)]);
export const oauthStates=sqliteTable('oauth_states',{id:text('id').primaryKey(),userId:text('user_id').notNull(),provider:text('provider').notNull(),verifier:text('verifier').notNull(),expires:integer('expires').notNull()});
export const customers=sqliteTable('customers',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),passwordHash:text('password_hash').notNull(),recoveryHash:text('recovery_hash').notNull(),createdAt:integer('created_at').notNull()});
export const customerSessions=sqliteTable('customer_sessions',{tokenHash:text('token_hash').primaryKey(),actorId:text('actor_id').notNull(),kind:text('kind').notNull(),expires:integer('expires').notNull()},t=>[index('customer_sessions_actor').on(t.actorId)]);
export const authLimits=sqliteTable('auth_limits',{key:text('key').primaryKey(),hits:integer('hits').notNull(),expires:integer('expires').notNull()});
export const whatsappBridge=sqliteTable('whatsapp_bridge',{id:text('id').primaryKey(),tokenHash:text('token_hash').notNull(),desired:text('desired').notNull().default('disconnected'),revision:integer('revision').notNull().default(0),state:text('state').notNull().default('offline'),qr:text('qr').notNull().default(''),phone:text('phone').notNull().default(''),lastSeen:integer('last_seen').notNull().default(0),runner:text('runner').notNull().default(''),leaseUntil:integer('lease_until').notNull().default(0)});
export const whatsappPairing=sqliteTable('whatsapp_pairing',{codeHash:text('code_hash').primaryKey(),expires:integer('expires').notNull()});
export const orderEvents=sqliteTable('order_events',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),event:text('event').notNull(),actor:text('actor').notNull(),createdAt:integer('created_at').notNull()},t=>[index('order_events_created').on(t.createdAt),index('order_events_order').on(t.orderId)]);
export const orderProofs=sqliteTable('order_proofs',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),objectKey:text('object_key').notNull(),createdAt:integer('created_at').notNull()},t=>[index('proof_order').on(t.orderId)]);
export const imageOriginals=sqliteTable('image_originals',{id:text('id').primaryKey(),objectKey:text('object_key').notNull(),contentType:text('content_type').notNull(),createdAt:integer('created_at').notNull()});
export const whatsappOutbox=sqliteTable('whatsapp_outbox',{event:text('event').notNull().default('Recebido'),id:text('id').primaryKey(),orderId:text('order_id').notNull(),recipient:text('recipient').notNull(),phone:text('phone').notNull(),status:text('status').notNull().default('queued'),leaseToken:text('lease_token').notNull().default(''),workerId:text('worker_id').notNull().default(''),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),messageId:text('message_id').notNull().default(''),detail:text('detail').notNull().default('')},t=>[index('whatsapp_outbox_status_created').on(t.status,t.createdAt)]);

export const receipts=sqliteTable('payment_receipts',{id:text('id').primaryKey(),orderId:text('order_id').notNull().references(()=>orders.id,{onDelete:'cascade'}),amount:integer('amount').notNull(),kind:text('kind').notNull(),method:text('method').notNull(),provider:text('provider').notNull(),actor:text('actor').notNull(),occurredAt:integer('occurred_at').notNull()},t=>[index('receipts_order_date').on(t.orderId,t.occurredAt),index('receipts_date').on(t.occurredAt)]);
export const cardAttempts=sqliteTable('card_attempts',{orderId:text('order_id').primaryKey().references(()=>orders.id,{onDelete:'cascade'}),attemptId:text('attempt_id').notNull(),tokenHash:text('token_hash').notNull(),state:text('state').notNull(),providerId:text('provider_id'),updatedAt:integer('updated_at').notNull()});

// A failed guard aborts the complete D1 batch, without relying on SQL triggers.
export const commerceGuards=sqliteTable('commerce_guards',{id:text('id').primaryKey(),valid:integer('valid').notNull()},t=>[check('commerce_guard_valid',sql`${t.valid}=1`)]);
